import type { TareaCatalogo } from '../types';

export const CATALOGO_02: TareaCatalogo[] = [
  {
    plantillaId: 'PB-02-01',
    nombreOriginal: 'Modelar redes de media tensión',
    nombre: 'Modelar la red de media tensión desde el punto de conexión del operador de red hasta la subestación',
    grupo: '02-modelado',
    subgrupo: 'Acometidas y subestación',
    categoria: 'Acometidas',
    disciplina: 'Eléctrica',
    dificultad: 3,
    dependeDe: ['PB-01-01'],
    guiaIds: ['M5.1', 'M2.1'],
    descripcion: 'Modelado en Revit del trazado de la red de media tensión (acometida MT) que conecta el punto de entrega del operador de red con la subestación del proyecto, incluyendo el trazado en planta y en profundidad.',
    objetivo: 'Representar en el modelo BIM la trayectoria física de la acometida en media tensión, coherente con la ubicación de subestación definida en el predimensionamiento.',
    requisitos: [
      'Ubicación de subestación definida (PB-01-01) confirmada en el modelo',
      'Levantamiento topográfico o planta de urbanismo vinculada',
      'Nivel de tensión de la red MT confirmado con el operador de red',
    ],
    procedimiento: [
      '1. Vincular el plano de urbanismo o topografía como referencia de fondo (Insertar > Vincular CAD).',
      '2. Crear o seleccionar el sistema eléctrico "Media tensión" en la categoría Conductores eléctricos.',
      '3. Trazar el recorrido del cable de MT desde el punto de conexión indicado por el operador de red hasta la celda de llegada de la subestación.',
      '4. Asignar el tipo de conductor y el parámetro de tensión nominal correspondiente a MT.',
      '5. Verificar las profundidades de enterramiento en las vistas de sección donde el trazado cruza vías o zonas duras.',
      '6. Coordinar el trazado con las redes de otras disciplinas (hidrosanitaria, gas) visibles en el modelo federado.',
    ],
    resultadoEsperado: 'Trazado continuo de la red de media tensión modelado en Revit, desde el punto de conexión hasta la subestación, con el tipo de conductor y la tensión nominal asignados.',
    criteriosVerificacion: [
      'El trazado de MT no presenta interrupciones entre el punto de conexión y la subestación.',
      'El parámetro de tensión nominal está asignado en todos los tramos del sistema.',
      'El trazado no cruza en planta ninguna red de otra disciplina sin punto de cruce validado.',
      'La profundidad de enterramiento indicada en las secciones es consistente en todo el recorrido.',
    ],
    notasIngenieria: [
      { texto: 'La acometida en media tensión hace parte de las instalaciones cubiertas por el RETIE; verificar con el operador de red los requisitos específicos de la zona antes de fijar el trazado definitivo.', fuente: null, verificar: true },
    ],
    tipsRevit: [
      'Usa la categoría "Conductores eléctricos" con el sistema "Cable Tray" o "Conduit" según se modele ducto o cable directamente enterrado.',
      'Activa una vista de sección a lo largo del trazado para revisar cruces con otras redes antes de fijar la cota de enterramiento.',
      'Usa "Copiar/Monitorear" en la pestaña Colaborar para heredar el punto de conexión del vínculo de urbanismo y evitar desfases de coordenadas.',
    ],
  },
  {
    plantillaId: 'PB-02-02',
    nombreOriginal: 'Modelar redes de baja tensión',
    nombre: 'Modelar la red de distribución en baja tensión desde la subestación hasta los tableros de cada bloque',
    grupo: '02-modelado',
    subgrupo: 'Distribución BT',
    categoria: 'Acometidas',
    disciplina: 'Eléctrica',
    dificultad: 3,
    dependeDe: ['PB-02-01'],
    guiaIds: ['M5.2', 'M2.1'],
    descripcion: 'Modelado de los circuitos alimentadores en baja tensión que distribuyen la energía desde el tablero general de la subestación hasta los tableros de distribución de cada bloque o torre.',
    objetivo: 'Dejar representada en el modelo la topología de distribución en BT que servirá de base para el cálculo de circuitos y la documentación de planos.',
    requisitos: [
      'Red de media tensión y subestación modeladas (PB-02-01)',
      'Listado de tableros generales por bloque definido',
      'Capacidad del transformador preliminar disponible (PB-01-04)',
    ],
    procedimiento: [
      '1. Ubicar el tablero general de baja tensión (TGBT) en la subestación dentro del modelo.',
      '2. Crear el sistema eléctrico de alimentadores en BT desde el TGBT hacia cada tablero de bloque.',
      '3. Trazar el recorrido físico de cada alimentador siguiendo las rutas de ductos previstas en el predimensionamiento (PB-01-03).',
      '4. Asignar calibre y tipo de conductor provisional a cada alimentador según la carga estimada del bloque.',
      '5. Verificar que cada tablero de bloque quede conectado a un único alimentador de origen sin bucles.',
      '6. Revisar en 3D que los alimentadores no interfieran con elementos estructurales del vínculo arquitectónico.',
    ],
    resultadoEsperado: 'Alimentadores de baja tensión modelados entre el TGBT de subestación y los tableros de cada bloque, con calibres asignados y sin interferencias con la estructura.',
    criteriosVerificacion: [
      'Cada tablero de bloque tiene un único alimentador de origen conectado.',
      'Todos los tramos de alimentador tienen calibre y tipo de conductor asignado.',
      'No existen bucles ni tramos huérfanos en el sistema de alimentadores.',
      'La revisión 3D no muestra interferencias entre alimentadores y elementos estructurales.',
    ],
    notasIngenieria: [
      { texto: 'La red de baja tensión y sus protecciones deben cumplir el RETIE en lo relativo a acometidas; confirmar los calibres definitivos únicamente tras el cálculo de cargas real.', fuente: null, verificar: true },
    ],
    tipsRevit: [
      'Usa "Sistema eléctrico" (Electrical System) para agrupar los alimentadores por tablero de origen y facilitar su identificación en tablas.',
      'Filtra la vista 3D por el parámetro "Sistema eléctrico" para aislar únicamente los alimentadores de BT durante la revisión de interferencias.',
      'Usa el parámetro "Longitud" del sistema eléctrico para validar que el recorrido modelado sea consistente con la distancia real entre tableros.',
    ],
  },
  {
    plantillaId: 'PB-02-03',
    nombreOriginal: 'Propuesta de salidas',
    nombre: 'Proponer la ubicación de las salidas de tomacorriente y fuerza en la planta arquitectónica',
    grupo: '02-modelado',
    subgrupo: 'Tomacorrientes y fuerza',
    categoria: 'Tomacorrientes',
    disciplina: 'Eléctrica',
    dificultad: 2,
    dependeDe: [],
    guiaIds: ['M5.5', 'M2.5'],
    descripcion: 'Definición inicial, sobre la planta arquitectónica vinculada, de la cantidad y ubicación aproximada de las salidas de tomacorriente normales y de fuerza requeridas por espacio.',
    objetivo: 'Establecer una propuesta de ubicación de salidas eléctricas que sirva de base para el modelado detallado de tomacorrientes en etapas posteriores.',
    requisitos: [
      'Planta arquitectónica vinculada y niveles verificados (PB-01-10)',
      'Programa de áreas o usos de cada espacio disponible',
    ],
    procedimiento: [
      '1. Revisar la planta arquitectónica vinculada e identificar el uso de cada espacio (habitación, cocina, zona común, cuarto técnico).',
      '2. Colocar familias de tomacorriente tipo "marcador" o placeholder en cada punto propuesto, usando la categoría Dispositivos eléctricos.',
      '3. Asignar el parámetro de tipo de salida (normal, fuerza, especial) a cada marcador.',
      '4. Contrastar la cantidad de salidas por espacio contra el criterio interno de diseño o el programa arquitectónico.',
      '5. Registrar en una tabla de planificación el conteo de salidas propuestas por nivel.',
    ],
    resultadoEsperado: 'Propuesta de ubicación de salidas de tomacorriente y fuerza colocada sobre la planta arquitectónica, con conteo por nivel y tipo de salida.',
    criteriosVerificacion: [
      'Todos los espacios habitables tienen al menos una salida propuesta.',
      'Cada marcador de salida tiene asignado el parámetro de tipo (normal, fuerza, especial).',
      'La tabla de planificación refleja el conteo real de marcadores colocados en el modelo.',
    ],
    notasIngenieria: [
      { texto: 'La cantidad mínima de salidas por espacio suele estar normada por el código eléctrico local; esta propuesta es un punto de partida sujeto a validación posterior, no un valor definitivo.', fuente: null, verificar: true },
    ],
    tipsRevit: [
      'Crea una familia de marcador liviana (sin geometría 3D compleja) para la propuesta inicial y así evitar peso de archivo innecesario.',
      'Usa una tabla de planificación de "Dispositivos eléctricos" agrupada por nivel y tipo para llevar el conteo mientras propones las salidas.',
      'Aplica un filtro de vista por parámetro de tipo de salida para revisar visualmente la distribución de normales vs. fuerza en la planta.',
    ],
  },
  {
    plantillaId: 'PB-02-04',
    nombreOriginal: 'Modelar redes de servicios comunes',
    nombre: 'Modelar las redes eléctricas de alimentación de las zonas de servicios comunes del proyecto',
    grupo: '02-modelado',
    subgrupo: 'Distribución BT',
    categoria: 'Modelado',
    disciplina: 'Eléctrica',
    dificultad: 3,
    dependeDe: ['PB-02-02'],
    guiaIds: ['M2.1', 'M5.2'],
    descripcion: 'Modelado de los circuitos que alimentan zonas comunes como parqueaderos, salones sociales, cuartos de bombas, portería y demás áreas compartidas del proyecto.',
    objetivo: 'Dejar completamente trazadas y conectadas las redes eléctricas de las zonas de uso común, diferenciadas de los circuitos privativos.',
    requisitos: [
      'Alimentadores de baja tensión modelados (PB-02-02)',
      'Listado de zonas comunes del proyecto arquitectónico',
    ],
    procedimiento: [
      '1. Identificar en la planta arquitectónica vinculada todas las zonas clasificadas como servicios comunes.',
      '2. Crear el tablero de servicios comunes (o los tableros por zona) dentro del modelo eléctrico.',
      '3. Trazar los circuitos desde el tablero de servicios comunes hacia cada carga identificada (bombas, portón, iluminación exterior común, etc.).',
      '4. Asignar el sistema eléctrico correspondiente a cada circuito para diferenciarlo de los circuitos privativos.',
      '5. Verificar en una tabla de planificación que ninguna carga de zona común quede conectada a un tablero privativo.',
    ],
    resultadoEsperado: 'Redes eléctricas de servicios comunes modeladas y conectadas a su tablero correspondiente, diferenciadas de los circuitos privativos del proyecto.',
    criteriosVerificacion: [
      'Todas las cargas identificadas como servicios comunes están conectadas al tablero de servicios comunes.',
      'Ningún circuito de zona común aparece conectado a un tablero privativo.',
      'Cada circuito de servicios comunes tiene asignado su sistema eléctrico.',
    ],
    notasIngenieria: [
      { texto: 'La separación de circuitos comunes y privativos es relevante para la facturación de energía por copropiedad; confirmar el criterio de agrupación con el diseño de conjunto antes de cerrar el modelado.', fuente: null, verificar: true },
    ],
    tipsRevit: [
      'Usa el parámetro compartido "Tipo de circuito" (común / privativo) para poder filtrar y auditar la separación desde una tabla de planificación.',
      'Agrupa los circuitos de servicios comunes en un "Sistema eléctrico" independiente por tablero para simplificar la lectura del diagrama unifilar.',
      'Verifica con el comando "Verificar sistema" (Check Circuit) que cada circuito común cierre correctamente antes de continuar con la documentación.',
    ],
  },
  {
    plantillaId: 'PB-02-05',
    nombreOriginal: 'Modelar iluminación y tomas foso de ascensor',
    nombre: 'Modelar la iluminación y las tomas eléctricas del foso del ascensor',
    grupo: '02-modelado',
    subgrupo: 'Iluminación',
    categoria: 'Iluminación',
    disciplina: 'Eléctrica',
    dificultad: 2,
    dependeDe: [],
    guiaIds: ['M5.4'],
    descripcion: 'Modelado de la luminaria y el tomacorriente de mantenimiento requeridos dentro del foso de ascensor, conforme a las dimensiones del foso definidas por el proveedor del equipo.',
    objetivo: 'Garantizar que el foso de ascensor cuente con iluminación y una toma de mantenimiento modeladas conforme a los requisitos del fabricante del ascensor.',
    requisitos: [
      'Ficha técnica del ascensor con dimensiones del foso',
      'Modelo arquitectónico del foso vinculado y verificado',
    ],
    procedimiento: [
      '1. Revisar la ficha técnica del ascensor para confirmar la posición requerida de luminaria y toma en el foso.',
      '2. Colocar la familia de luminaria de foso en la posición indicada, hospedada en el muro o losa del foso.',
      '3. Colocar la familia de tomacorriente de mantenimiento junto al acceso al foso.',
      '4. Crear el circuito que alimenta la luminaria y la toma del foso desde el tablero más cercano.',
      '5. Verificar en una vista de sección que la altura de montaje de ambos elementos cumpla lo indicado por el fabricante.',
    ],
    resultadoEsperado: 'Luminaria y toma de mantenimiento del foso de ascensor modeladas en la posición y altura indicadas por el fabricante, conectadas a un circuito.',
    criteriosVerificacion: [
      'La luminaria del foso está hospedada en el elemento correcto (muro o losa del foso).',
      'La toma de mantenimiento está ubicada junto al acceso al foso según la ficha técnica.',
      'Ambos elementos están conectados al mismo circuito o al circuito indicado para el cuarto de máquinas.',
      'La altura de montaje verificada en sección coincide con la especificación del fabricante.',
    ],
    notasIngenieria: [],
    tipsRevit: [
      'Usa una familia de luminaria hospedada en cara (face-based) para que se ajuste automáticamente a la geometría del foso si esta cambia.',
      'Activa la vista de sección "Foso de ascensor" desde el vínculo arquitectónico para validar alturas sin necesidad de crear una vista nueva.',
      'Verifica el parámetro "Nivel de referencia" de la luminaria y la toma para asegurar que midan la altura desde el fondo real del foso y no desde el nivel del piso del edificio.',
    ],
  },
  {
    plantillaId: 'PB-02-06',
    nombreOriginal: 'Modelar vertical tomas de gabinetes',
    nombre: 'Modelar el ramal vertical de alimentación a las tomas de los gabinetes de medidores',
    grupo: '02-modelado',
    subgrupo: 'Tomacorrientes y fuerza',
    categoria: 'Tomacorrientes',
    disciplina: 'Eléctrica',
    dificultad: 3,
    dependeDe: ['PB-02-02'],
    guiaIds: ['M5.5', 'M2.5'],
    descripcion: 'Modelado del ducto vertical (shaft eléctrico) y los circuitos que alimentan las tomas ubicadas en los gabinetes de medidores de cada piso.',
    objetivo: 'Representar el recorrido vertical completo, piso a piso, que alimenta las tomas de los gabinetes de medidores desde su origen.',
    requisitos: [
      'Alimentadores de baja tensión modelados (PB-02-02)',
      'Ubicación del shaft eléctrico confirmada en todos los niveles',
    ],
    procedimiento: [
      '1. Verificar en el modelo vinculado que el shaft eléctrico está alineado en todos los niveles del edificio.',
      '2. Crear el circuito vertical de alimentación a tomas de gabinetes usando una vista de sección o alzado que abarque todos los pisos.',
      '3. Colocar la toma de cada gabinete de medidores en cada nivel y conectarla al ramal vertical correspondiente.',
      '4. Asignar el calibre de conductor del ramal vertical según el número de pisos servidos.',
      '5. Revisar en 3D que el ramal vertical no presente desalineaciones entre niveles.',
      '6. Confirmar en una tabla de planificación que cada gabinete de medidores tiene su toma conectada.',
    ],
    resultadoEsperado: 'Ramal vertical de alimentación a tomas de gabinetes modelado y alineado en todos los niveles, con cada toma de gabinete conectada.',
    criteriosVerificacion: [
      'El ramal vertical está alineado (sin desfases en planta) en todos los niveles del shaft.',
      'Cada gabinete de medidores tiene su toma conectada al ramal vertical.',
      'El calibre del ramal vertical está asignado según el número de pisos servidos.',
      'No hay tramos del ramal vertical desconectados entre niveles consecutivos.',
    ],
    notasIngenieria: [],
    tipsRevit: [
      'Usa una vista de alzado o sección "Shaft eléctrico" que corte todos los niveles para modelar el ramal vertical de una sola vez.',
      'Habilita "Restricciones de nivel" (Base Level / Top Level) en el conducto vertical para que se ajuste automáticamente si cambia la altura de piso a piso.',
      'Usa el comando "Alinear" con la opción de alineación múltiple para verificar que los tramos verticales de cada piso queden centrados en el shaft.',
    ],
  },
  {
    plantillaId: 'PB-02-07',
    nombreOriginal: 'Caja de puesta a tierra en armarios',
    nombre: 'Modelar la caja de puesta a tierra en los armarios de medidores',
    grupo: '02-modelado',
    subgrupo: 'Puesta a tierra y apantallamiento',
    categoria: 'Sistemas Especiales',
    disciplina: 'Eléctrica',
    dificultad: 2,
    dependeDe: [],
    guiaIds: ['M5.6'],
    descripcion: 'Colocación en el modelo de la caja de puesta a tierra asociada a cada armario o cuarto de medidores, como punto de conexión del sistema de puesta a tierra.',
    objetivo: 'Dejar modelada la caja de puesta a tierra de cada armario de medidores en la posición correcta respecto al tablero y al conductor de tierra.',
    requisitos: [
      'Ubicación de armarios de medidores confirmada en el modelo arquitectónico',
    ],
    procedimiento: [
      '1. Ubicar cada armario de medidores en el modelo arquitectónico vinculado.',
      '2. Colocar la familia de caja de puesta a tierra junto a cada armario, respetando la distancia mínima al piso terminado indicada en el diseño.',
      '3. Conectar la caja de puesta a tierra al conductor de tierra del armario mediante el sistema eléctrico de puesta a tierra.',
      '4. Verificar en una tabla de planificación que exista una caja de puesta a tierra por cada armario de medidores modelado.',
    ],
    resultadoEsperado: 'Caja de puesta a tierra modelada junto a cada armario de medidores y conectada al sistema de puesta a tierra del proyecto.',
    criteriosVerificacion: [
      'Existe una caja de puesta a tierra por cada armario de medidores del modelo.',
      'Cada caja está conectada al conductor de puesta a tierra del armario correspondiente.',
      'La posición de la caja respeta la distancia al piso terminado definida en el diseño.',
    ],
    notasIngenieria: [
      { texto: 'Las cajas de puesta a tierra y su conexión a los armarios de medición hacen parte del sistema de puesta a tierra regulado por el RETIE; confirmar el detalle constructivo exacto con el diseño de puesta a tierra del proyecto.', fuente: null, verificar: true },
    ],
    tipsRevit: [
      'Modela la caja de puesta a tierra como familia basada en el suelo (hospedada en Piso) para que su cota se ajuste automáticamente al nivel del proyecto.',
      'Usa el sistema "Conductor de puesta a tierra" dentro de Sistemas eléctricos para diferenciar visualmente esta red de los circuitos de fuerza.',
      'Agrega una tabla de planificación filtrada por la familia de caja de puesta a tierra para auditar rápidamente que no falte ninguna junto a un armario.',
    ],
  },
  {
    plantillaId: 'PB-02-08',
    nombreOriginal: 'Malla de puesta a tierra',
    nombre: 'Modelar la malla de puesta a tierra de la subestación',
    grupo: '02-modelado',
    subgrupo: 'Puesta a tierra y apantallamiento',
    categoria: 'Sistemas Especiales',
    disciplina: 'Eléctrica',
    dificultad: 3,
    dependeDe: ['PB-01-01'],
    guiaIds: ['M5.6'],
    descripcion: 'Modelado de la malla de puesta a tierra de la subestación, incluyendo conductores de la malla, varillas de puesta a tierra y puntos de conexión a equipos.',
    objetivo: 'Representar en el modelo la malla de puesta a tierra de la subestación como base para la documentación de planos de SPT (sistema de puesta a tierra).',
    requisitos: [
      'Ubicación y dimensiones de la subestación definidas (PB-01-01)',
      'Estudio de resistividad del terreno disponible, si aplica',
    ],
    procedimiento: [
      '1. Trazar el perímetro de la malla de puesta a tierra en planta, dentro del área de la subestación.',
      '2. Modelar los conductores de la malla como sistema eléctrico de puesta a tierra, respetando el retículo de diseño.',
      '3. Colocar las varillas de puesta a tierra en los puntos de cruce o extremos definidos en el diseño.',
      '4. Conectar cada equipo de la subestación (transformador, tablero general, celdas) a la malla mediante bajantes de puesta a tierra.',
      '5. Verificar en 3D que todos los equipos de la subestación tengan al menos una conexión a la malla.',
    ],
    resultadoEsperado: 'Malla de puesta a tierra de la subestación modelada con sus varillas y conductores, con todos los equipos conectados mediante bajantes.',
    criteriosVerificacion: [
      'La malla de puesta a tierra forma un circuito cerrado sin tramos huérfanos.',
      'Todos los equipos principales de la subestación tienen al menos una conexión a la malla.',
      'Las varillas de puesta a tierra están ubicadas en los puntos definidos en el diseño.',
      'No existen cruces de la malla con otras redes sin un punto de conexión validado.',
    ],
    notasIngenieria: [
      { texto: 'El sistema de puesta a tierra de la subestación está sujeto a los requisitos del RETIE; el valor de resistencia de puesta a tierra exigido depende del estudio de resistividad del terreno y no debe asumirse en el modelado.', fuente: null, verificar: true },
    ],
    tipsRevit: [
      'Modela la malla de puesta a tierra como un sistema eléctrico independiente, distinto del sistema de conductores de fuerza, para poder aislarla en el diagrama unifilar.',
      'Usa una familia genérica basada en línea para las varillas de puesta a tierra y así facilitar su conteo en una tabla de planificación.',
      'Activa una vista 3D con caja de sección (Section Box) limitada al área de subestación para revisar visualmente que cada bajante llegue efectivamente a la malla.',
    ],
  },
  {
    plantillaId: 'PB-02-09',
    nombreOriginal: 'Creación de circuitos (uno por tipología)',
    nombre: 'Crear un circuito eléctrico representativo por cada tipología de unidad del proyecto',
    grupo: '02-modelado',
    subgrupo: 'Distribución BT',
    categoria: 'Tableros',
    disciplina: 'Eléctrica',
    dificultad: 3,
    dependeDe: ['PB-02-03'],
    guiaIds: ['M5.3'],
    descripcion: 'Creación, en el modelo, de un circuito eléctrico completo (tomas e iluminación conectadas a un panel) para cada tipología de apartamento o unidad definida en el proyecto arquitectónico, como base replicable para el resto de unidades iguales.',
    objetivo: 'Contar con un circuito modelado y verificado por cada tipología, que sirva de plantilla para replicar en las unidades restantes del mismo tipo.',
    requisitos: [
      'Propuesta de salidas definida (PB-02-03)',
      'Listado de tipologías de unidad del proyecto arquitectónico',
    ],
    procedimiento: [
      '1. Identificar en el modelo arquitectónico las tipologías de unidad distintas (por ejemplo, apartamento tipo A, tipo B).',
      '2. Seleccionar una unidad representativa de cada tipología en el modelo eléctrico.',
      '3. Crear el sistema eléctrico de fuerza o iluminación seleccionando todas las salidas de la unidad y asignándolas a un circuito.',
      '4. Conectar el circuito creado al panel de distribución correspondiente a esa unidad.',
      '5. Verificar en la tabla de planificación de paneles que el circuito muestra la carga conectada y el número de salidas correcto.',
      '6. Documentar el circuito tipo como referencia para la replicación en las demás unidades de la misma tipología.',
    ],
    resultadoEsperado: 'Un circuito eléctrico completo y verificado por cada tipología de unidad, conectado a su panel correspondiente y listo como plantilla de replicación.',
    criteriosVerificacion: [
      'Existe al menos un circuito creado por cada tipología de unidad identificada.',
      'Cada circuito está conectado a un panel de distribución válido.',
      'La tabla de planificación del panel muestra la carga conectada del circuito sin valores en cero o vacíos.',
      'El número de salidas del circuito coincide con el número de salidas propuestas para esa unidad (PB-02-03).',
    ],
    notasIngenieria: [],
    tipsRevit: [
      'Selecciona las salidas y usa el comando de creación de "Sistema eléctrico" (Power) desde la pestaña Sistemas para crear el circuito directamente.',
      'Usa la tabla de planificación de paneles (Panel Schedule) del tablero para revisar de inmediato la carga conectada tras crear el circuito.',
      'Nombra el circuito con un identificador que incluya la tipología (por ejemplo "TIPO-A-C1") para facilitar su localización al momento de replicar en otras unidades.',
    ],
  },
  {
    plantillaId: 'PB-02-10',
    nombreOriginal: 'Ubicación de interruptores y salidas',
    nombre: 'Ubicar los interruptores (breakers) en los tableros y verificar su conexión con las salidas asociadas',
    grupo: '02-modelado',
    subgrupo: 'Distribución BT',
    categoria: 'Modelado',
    disciplina: 'Eléctrica',
    dificultad: 2,
    dependeDe: ['PB-02-09'],
    guiaIds: ['M5.3', 'M5.2'],
    descripcion: 'Verificación y ajuste, dentro de la tabla de planificación del panel, de la posición de cada interruptor (breaker) y su correspondencia con las salidas conectadas al circuito.',
    objetivo: 'Asegurar que cada interruptor del tablero corresponda a un circuito con salidas conectadas y que su posición en el panel sea coherente con el balanceo de fases.',
    requisitos: [
      'Circuitos creados para al menos una tipología (PB-02-09)',
      'Panel de distribución modelado con sus fases definidas',
    ],
    procedimiento: [
      '1. Abrir la tabla de planificación (Panel Schedule) del tablero a revisar.',
      '2. Verificar que cada circuito creado tenga un interruptor asignado en una posición del panel.',
      '3. Revisar la distribución de circuitos entre fases para evitar desbalanceo evidente.',
      '4. Confirmar en el modelo 3D que las salidas asociadas a cada interruptor corresponden al circuito correcto.',
      '5. Ajustar la posición de los interruptores en la tabla de planificación cuando se detecte un cruce de circuitos.',
    ],
    resultadoEsperado: 'Interruptores del tablero ubicados en posiciones correctas dentro del panel, con correspondencia verificada entre cada breaker y sus salidas conectadas.',
    criteriosVerificacion: [
      'Cada circuito tiene un interruptor asignado a una posición válida del panel.',
      'No hay dos circuitos distintos asignados a la misma posición del panel.',
      'La distribución de circuitos entre fases no muestra un desbalanceo evidente entre columnas.',
      'Las salidas mostradas en el modelo 3D corresponden al circuito indicado en la tabla de planificación.',
    ],
    notasIngenieria: [],
    tipsRevit: [
      'Usa la vista "Panel Schedule" del tablero y el parámetro "Circuit Number" para reordenar interruptores arrastrando filas directamente en la tabla.',
      'Aplica un filtro de vista por "Circuit Number" en la vista 3D para resaltar únicamente las salidas de un interruptor específico durante la verificación.',
      'Revisa el parámetro "Load Classification" de cada circuito para confirmar que el balanceo de fases considera el tipo de carga real.',
    ],
  },
  {
    plantillaId: 'PB-02-11',
    nombreOriginal: 'Modelar apantallamiento',
    nombre: 'Modelar el sistema de apantallamiento (pararrayos) de la edificación',
    grupo: '02-modelado',
    subgrupo: 'Puesta a tierra y apantallamiento',
    categoria: 'Sistemas Especiales',
    disciplina: 'Eléctrica',
    dificultad: 4,
    dependeDe: [],
    guiaIds: ['M5.6'],
    descripcion: 'Modelado del sistema de apantallamiento contra rayos, incluyendo puntas captadoras, conductores de bajada y su conexión al sistema de puesta a tierra, según el nivel de protección definido para el proyecto.',
    objetivo: 'Representar en el modelo el sistema de apantallamiento completo, coherente con el nivel de protección y el método de diseño adoptado para el proyecto.',
    requisitos: [
      'Nivel de protección contra rayos (NPR) definido para el proyecto',
      'Malla de puesta a tierra modelada o en proceso (PB-02-08)',
      'Volumetría final de cubierta del modelo arquitectónico vinculada',
    ],
    procedimiento: [
      '1. Confirmar el nivel de protección contra rayos y el método de diseño (malla, punta Franklin o electrogeométrico) definidos para el proyecto.',
      '2. Colocar las puntas captadoras en cubierta según el método de diseño adoptado.',
      '3. Modelar los conductores de bajada desde cada punta captadora hasta el punto de conexión con la malla de puesta a tierra.',
      '4. Conectar cada bajante al sistema de puesta a tierra modelado (PB-02-08).',
      '5. Verificar en 3D que ninguna bajante quede sin conexión a la malla de puesta a tierra.',
      '6. Revisar que la cantidad y posición de las puntas captadoras sea consistente con el estudio de apantallamiento del proyecto.',
    ],
    resultadoEsperado: 'Sistema de apantallamiento modelado con puntas captadoras, bajantes y conexión completa al sistema de puesta a tierra del proyecto.',
    criteriosVerificacion: [
      'Cada punta captadora tiene al menos una bajante conectada.',
      'Todas las bajantes llegan a un punto de conexión válido en la malla de puesta a tierra.',
      'La cantidad de puntas captadoras coincide con la definida en el estudio de apantallamiento del proyecto.',
      'No existen bajantes que atraviesen espacios habitables sin la protección o el retiro definido en el diseño.',
    ],
    notasIngenieria: [
      { texto: 'El diseño del sistema de apantallamiento contra rayos está regulado por el RETIE; el método de cálculo (malla, Franklin o electrogeométrico) y el nivel de protección deben provenir del estudio de apantallamiento, no asumirse durante el modelado.', fuente: null, verificar: true },
    ],
    tipsRevit: [
      'Modela las puntas captadoras como familias basadas en cara para que se adapten a la geometría real de la cubierta del vínculo arquitectónico.',
      'Usa un sistema eléctrico independiente llamado "Apantallamiento" para poder aislarlo del resto de sistemas de puesta a tierra en el diagrama.',
      'Activa "Copiar/Monitorear" sobre el vínculo de cubierta para que las puntas captadoras se actualicen si cambia la volumetría de la cubierta.',
    ],
  },
  {
    plantillaId: 'PB-02-12',
    nombreOriginal: 'Crear toma normal y trifásica en la planta',
    nombre: 'Crear las tomas normales y trifásicas en la planta arquitectónica del proyecto',
    grupo: '02-modelado',
    subgrupo: 'Tomacorrientes y fuerza',
    categoria: 'Tomacorrientes',
    disciplina: 'Eléctrica',
    dificultad: 2,
    dependeDe: ['PB-02-03'],
    guiaIds: ['M5.5'],
    descripcion: 'Reemplazo de los marcadores de la propuesta de salidas por las familias definitivas de toma normal y toma trifásica en cada punto de la planta arquitectónica.',
    objetivo: 'Dejar modeladas con la familia definitiva todas las tomas normales y trifásicas propuestas para la planta del proyecto.',
    requisitos: [
      'Propuesta de salidas aprobada (PB-02-03)',
      'Familias de toma normal y toma trifásica cargadas en el proyecto',
    ],
    procedimiento: [
      '1. Cargar en el proyecto las familias definitivas de toma normal y toma trifásica.',
      '2. Reemplazar cada marcador de la propuesta de salidas por la familia definitiva correspondiente según su tipo.',
      '3. Verificar la altura de montaje de cada toma según el criterio de diseño del proyecto (tomas normales vs. tomas especiales).',
      '4. Confirmar que cada toma quede hospedada en el muro o superficie correcta del modelo arquitectónico.',
      '5. Revisar en una tabla de planificación que el conteo final de tomas coincide con la propuesta original.',
    ],
    resultadoEsperado: 'Todas las tomas normales y trifásicas de la planta modeladas con su familia definitiva, en la altura y posición correctas.',
    criteriosVerificacion: [
      'Ningún marcador de propuesta permanece en el modelo tras el reemplazo.',
      'Cada toma trifásica está identificada con el parámetro de tipo correcto, distinto al de toma normal.',
      'La altura de montaje de las tomas corresponde al criterio de diseño definido.',
      'El conteo de tomas en la tabla de planificación coincide con el de la propuesta de salidas (PB-02-03).',
    ],
    notasIngenieria: [],
    tipsRevit: [
      'Usa el comando "Reemplazar familia" desde el navegador de proyecto para sustituir en bloque los marcadores por la familia definitiva sin perder su ubicación.',
      'Verifica el parámetro de tipo de familia (número de polos) para diferenciar tomas trifásicas de tomas normales en la tabla de planificación.',
      'Usa una plantilla de vista con filtro por tipo de toma para revisar visualmente la distribución antes de dar por cerrada la planta.',
    ],
  },
  {
    plantillaId: 'PB-02-13',
    nombreOriginal: 'Crear toma normal y trifásica en el cuarto de armarios',
    nombre: 'Crear las tomas normales y trifásicas del cuarto de armarios de medidores',
    grupo: '02-modelado',
    subgrupo: 'Tomacorrientes y fuerza',
    categoria: 'Tomacorrientes',
    disciplina: 'Eléctrica',
    dificultad: 2,
    dependeDe: ['PB-02-03'],
    guiaIds: ['M5.5'],
    descripcion: 'Modelado de las tomas normales y trifásicas destinadas al cuarto de armarios de medidores, requeridas para labores de mantenimiento y equipos del cuarto.',
    objetivo: 'Dejar modeladas las tomas de mantenimiento del cuarto de armarios de medidores, con su circuito de alimentación asociado.',
    requisitos: [
      'Propuesta de salidas del cuarto de armarios definida (PB-02-03)',
      'Ubicación del cuarto de armarios confirmada en el modelo arquitectónico',
    ],
    procedimiento: [
      '1. Ubicar el cuarto de armarios de medidores en el modelo arquitectónico vinculado.',
      '2. Colocar la familia definitiva de toma normal en el punto propuesto para mantenimiento general.',
      '3. Colocar la familia definitiva de toma trifásica si el cuarto requiere alimentar equipos trifásicos.',
      '4. Conectar ambas tomas a un circuito del tablero que sirve el cuarto de armarios.',
      '5. Verificar que la posición de las tomas no interfiera con la apertura de puertas de los armarios.',
    ],
    resultadoEsperado: 'Tomas normales y trifásicas del cuarto de armarios de medidores modeladas y conectadas a su circuito de alimentación.',
    criteriosVerificacion: [
      'El cuarto de armarios cuenta con al menos una toma normal modelada.',
      'La toma trifásica está presente si el cuarto tiene equipos que la requieran, según la propuesta de salidas.',
      'Ambas tomas están conectadas a un circuito válido del tablero que sirve el cuarto.',
      'La posición de las tomas no interfiere con la apertura de puertas de los armarios en el modelo 3D.',
    ],
    notasIngenieria: [],
    tipsRevit: [
      'Revisa la vista 3D con la puerta de los armarios en posición abierta (parámetro de familia) para confirmar que la toma no queda obstruida.',
      'Usa el mismo circuito del cuarto de armarios para ambas tomas cuando la carga total lo permita, y verifícalo en la tabla de planificación del panel.',
      'Aplica la etiqueta de "Panel" y "Circuit Number" visible en la vista de planta para facilitar la trazabilidad durante la revisión de obra.',
    ],
  },
  {
    plantillaId: 'PB-02-14',
    nombreOriginal: 'Modelar tubería salidas',
    nombre: 'Modelar la tubería de canalización eléctrica para las salidas de tomacorriente y fuerza',
    grupo: '02-modelado',
    subgrupo: 'Canalizaciones',
    categoria: 'Ductos y Bandejas',
    disciplina: 'Eléctrica',
    dificultad: 2,
    dependeDe: ['PB-02-12'],
    guiaIds: ['M2.1', 'M2.2'],
    descripcion: 'Modelado de la tubería (conduit) que canaliza los conductores desde cada tomacorriente o salida de fuerza hasta la caja de paso o el tablero correspondiente.',
    objetivo: 'Dejar modelada la canalización física completa entre cada salida de tomacorriente/fuerza y su punto de conexión, lista para el cálculo de cantidades.',
    requisitos: [
      'Tomas normales y trifásicas modeladas en planta (PB-02-12, PB-02-13)',
      'Circuitos de tomacorriente ya creados',
    ],
    procedimiento: [
      '1. Seleccionar el sistema eléctrico de cada circuito de tomacorriente/fuerza a canalizar.',
      '2. Usar el comando de generación automática de conductos ("Generate Layout") o modelar manualmente con "Conduit" para trazar la tubería entre cada salida y la caja de paso.',
      '3. Ajustar el trazado para respetar retiros mínimos a otras canalizaciones y elementos estructurales.',
      '4. Asignar el diámetro de tubería según el número y calibre de conductores que contendrá.',
      '5. Verificar en 3D que toda salida de tomacorriente quede conectada a la red de tubería, sin tramos sueltos.',
      '6. Revisar en una tabla de planificación la longitud total de tubería modelada por tramo.',
    ],
    resultadoEsperado: 'Red de tubería para salidas de tomacorriente y fuerza modelada completamente, conectando cada toma con su caja de paso o tablero.',
    criteriosVerificacion: [
      'Toda toma normal o trifásica modelada tiene un tramo de tubería conectado.',
      'No existen tramos de tubería sueltos sin conexión en ambos extremos.',
      'El diámetro de cada tramo está asignado según el número de conductores que contiene.',
      'La tabla de planificación de tubería no muestra longitudes en cero para ningún tramo activo.',
    ],
    notasIngenieria: [],
    tipsRevit: [
      'Usa el comando "Generate Layout" desde la pestaña Sistemas para trazar automáticamente la tubería del circuito seleccionado y luego ajusta manualmente los tramos que crucen zonas críticas.',
      'Configura las reglas de dimensionamiento (Sizing Settings) del sistema de conductos antes de generar el trazado para que el diámetro se calcule automáticamente.',
      'Usa una tabla de planificación de "Conduit" agrupada por sistema para revisar la longitud total y detectar tramos con longitud cero.',
    ],
  },
  {
    plantillaId: 'PB-02-15',
    nombreOriginal: 'Modelar tubería iluminación',
    nombre: 'Modelar la tubería de canalización eléctrica para los circuitos de iluminación',
    grupo: '02-modelado',
    subgrupo: 'Canalizaciones',
    categoria: 'Ductos y Bandejas',
    disciplina: 'Eléctrica',
    dificultad: 2,
    dependeDe: ['PB-02-05'],
    guiaIds: ['M2.1', 'M2.2'],
    descripcion: 'Modelado de la tubería (conduit) que canaliza los conductores de los circuitos de iluminación desde cada luminaria o punto de control hasta la caja de paso o el tablero correspondiente.',
    objetivo: 'Dejar modelada la canalización física completa de los circuitos de iluminación, lista para el cálculo de cantidades y la documentación.',
    requisitos: [
      'Luminarias e interruptores de control modelados en planta',
      'Circuitos de iluminación ya creados',
    ],
    procedimiento: [
      '1. Seleccionar el sistema eléctrico de cada circuito de iluminación a canalizar.',
      '2. Trazar la tubería entre cada luminaria, su interruptor de control y la caja de paso correspondiente.',
      '3. Ajustar el trazado en cielos falsos o losas según el criterio constructivo del proyecto.',
      '4. Asignar el diámetro de tubería según el número y calibre de conductores que contendrá.',
      '5. Verificar en 3D que toda luminaria e interruptor queden conectados a la red de tubería modelada.',
      '6. Revisar en una tabla de planificación la longitud total de tubería de iluminación por tramo.',
    ],
    resultadoEsperado: 'Red de tubería para circuitos de iluminación modelada completamente, conectando luminarias, interruptores y cajas de paso.',
    criteriosVerificacion: [
      'Toda luminaria modelada tiene un tramo de tubería conectado hasta su interruptor de control.',
      'No existen tramos de tubería sueltos sin conexión en ambos extremos.',
      'El diámetro de cada tramo está asignado según el número de conductores que contiene.',
      'La tabla de planificación de tubería de iluminación no muestra longitudes en cero para ningún tramo activo.',
    ],
    notasIngenieria: [],
    tipsRevit: [
      'Traza primero los tramos entre interruptor y luminaria antes de usar el trazado automático, ya que el orden de conexión define el recorrido de "Generate Layout".',
      'Usa la vista de cielo falso reflejado (Reflected Ceiling Plan) para ubicar con precisión el trazado de tubería respecto a la disposición real de luminarias.',
      'Filtra la tabla de planificación de "Conduit" por el sistema de iluminación para separar su longitud de la tubería de tomacorriente al calcular cantidades.',
    ],
  },
  {
    plantillaId: 'PB-02-16',
    nombreOriginal: 'Cálculo de transformador',
    nombre: 'Recalcular y verificar la capacidad definitiva del transformador con las cargas del proyecto arquitectónico',
    grupo: '02-modelado',
    subgrupo: 'Acometidas y subestación',
    categoria: 'Acometidas',
    disciplina: 'Eléctrica',
    dificultad: 4,
    dependeDe: ['PB-01-04'],
    guiaIds: ['M5.1'],
    descripcion: 'Recálculo de la capacidad del transformador a partir de la carga instalada real, obtenida de los circuitos y tableros ya modelados del proyecto arquitectónico, para confirmar o ajustar la capacidad estimada en el predimensionamiento.',
    objetivo: 'Verificar que la capacidad del transformador seleccionada en el predimensionamiento (PB-01-04) sea suficiente para la carga real del proyecto ya modelado, y ajustarla si es necesario.',
    requisitos: [
      'Cálculo preliminar del transformador disponible (PB-01-04)',
      'Tableros y circuitos del proyecto modelados con sus cargas conectadas',
      'Factores de demanda y coincidencia definidos para el tipo de proyecto',
    ],
    procedimiento: [
      '1. Extraer del modelo, mediante tablas de planificación de paneles, la carga instalada total de todos los tableros del proyecto.',
      '2. Aplicar los factores de demanda y coincidencia correspondientes a cada tipo de carga (iluminación, tomas, fuerza, servicios comunes).',
      '3. Calcular la demanda máxima proyectada resultante en kVA.',
      '4. Comparar la demanda máxima calculada contra la capacidad del transformador estimada en el cálculo preliminar (PB-01-04).',
      '5. Ajustar la capacidad nominal del transformador en el modelo si la demanda real supera o queda muy por debajo de la capacidad preliminar.',
      '6. Documentar la memoria de cálculo definitiva con la carga instalada, los factores aplicados y la capacidad final seleccionada.',
    ],
    resultadoEsperado: 'Capacidad definitiva del transformador verificada o ajustada a partir de la carga real del proyecto modelado, con memoria de cálculo documentada.',
    criteriosVerificacion: [
      'La carga instalada total fue extraída de las tablas de planificación de paneles del modelo, no estimada manualmente.',
      'Los factores de demanda aplicados están documentados en la memoria de cálculo.',
      'La capacidad nominal del transformador en el modelo coincide con el resultado del cálculo definitivo.',
      'La memoria de cálculo compara explícitamente el resultado definitivo contra el cálculo preliminar (PB-01-04).',
    ],
    notasIngenieria: [
      { texto: 'El dimensionamiento del transformador y su acometida en media/baja tensión están sujetos al RETIE; la capacidad final debe quedar respaldada por la memoria de cálculo definitiva, no solo por el predimensionamiento.', fuente: null, verificar: true },
      { texto: 'Los factores de demanda y coincidencia dependen del tipo de proyecto y de la normativa del operador de red local; no asumir valores fijos sin confirmarlos con el código eléctrico aplicable.', fuente: null, verificar: true },
    ],
    tipsRevit: [
      'Usa una tabla de planificación de "Panel Schedule" a nivel de proyecto para sumar la carga conectada de todos los tableros sin recalcular manualmente fuera de Revit.',
      'Registra el resultado del cálculo definitivo en un parámetro compartido de la subestación (por ejemplo "Capacidad_Transformador_kVA") para que quede trazable en el modelo.',
      'Compara el parámetro de capacidad preliminar (PB-01-04) y definitivo en la misma tabla de planificación de equipo para evidenciar el ajuste ante el equipo de diseño.',
    ],
  },
  {
    plantillaId: 'PB-02-17',
    nombreOriginal: 'Cálculo del dámper',
    nombre: 'Calcular las dimensiones del dámper de ventilación de la subestación',
    grupo: '02-modelado',
    subgrupo: 'Acometidas y subestación',
    categoria: 'Modelado',
    disciplina: 'Eléctrica',
    dificultad: 3,
    dependeDe: ['PB-01-01', 'PB-02-16'],
    guiaIds: ['M5.1'],
    descripcion: 'Cálculo del área de ventilación (dámper) requerida para la disipación térmica del cuarto de transformador, a partir de las pérdidas de potencia del transformador seleccionado.',
    objetivo: 'Determinar el área de dámper de ventilación necesaria para el cuarto de subestación, en función de la capacidad definitiva del transformador.',
    requisitos: [
      'Capacidad definitiva del transformador calculada (PB-02-16)',
      'Dimensiones del cuarto de subestación confirmadas en el modelo',
    ],
    procedimiento: [
      '1. Obtener las pérdidas de potencia (en watts) del transformador según su capacidad definitiva (PB-02-16).',
      '2. Calcular el área de ventilación requerida a partir de las pérdidas térmicas y el criterio de diseño adoptado para el proyecto.',
      '3. Verificar en el modelo las dimensiones disponibles en el muro o losa donde se ubicará el dámper.',
      '4. Modelar el dámper con el área calculada, hospedado en el elemento arquitectónico correspondiente.',
      '5. Confirmar que el área modelada del dámper sea igual o mayor al área mínima calculada.',
    ],
    resultadoEsperado: 'Dámper de ventilación de la subestación modelado con el área calculada a partir de las pérdidas térmicas del transformador definitivo.',
    criteriosVerificacion: [
      'El área del dámper modelado es igual o mayor al área mínima resultante del cálculo.',
      'El cálculo del área de ventilación referencia explícitamente la capacidad definitiva del transformador (PB-02-16).',
      'El dámper está hospedado en un elemento arquitectónico real del cuarto de subestación, no como elemento flotante.',
    ],
    notasIngenieria: [
      { texto: 'El área de ventilación de cuartos de transformador suele estar sujeta a criterios de disipación térmica del fabricante del equipo y a normativa de seguridad de subestaciones; no asumir un valor de área fijo sin confirmar el criterio de cálculo del proyecto.', fuente: null, verificar: true },
    ],
    tipsRevit: [
      'Modela el dámper como familia basada en muro (wall-based) para que su posición se mantenga asociada al cerramiento del cuarto de subestación.',
      'Registra el área calculada y el área modelada en parámetros compartidos separados para poder auditar la diferencia desde una tabla de planificación.',
      'Usa una vista de alzado del cuarto de subestación para verificar que la altura de montaje del dámper permita el flujo de aire cruzado con las aberturas opuestas.',
    ],
  },
];
