import { REF, notaCriterio, notaNorma, notaNormaVerificar } from './normas';
import type { TareaCatalogo } from '../types';

export const CATALOGO_02: TareaCatalogo[] = [
  {
    plantillaId: 'PB-02-01',
    nombreOriginal: 'Modelar redes de media tensión',
    nombre: 'Modelar la red de media tensión desde el punto de conexión del operador de red hasta la subestación',
    grupo: '02-modelado',
    subgrupo: 'Acometidas y subestación',
    categoria: 'Acometidas',
    disciplina: 'Eléctrica',
    dificultad: 3,
    horasEstimadas: 8,
    prioridad: 'Alta',
    dependeDe: ['PB-01-01'],
    guiaIds: ['M5.1', 'M2.1'],
    descripcion: 'Modelado en Revit del trazado de la red de media tensión (acometida MT) que conecta el punto de entrega del operador de red con la subestación del proyecto, incluyendo el trazado en planta y en profundidad.',
    objetivo: 'Representar en el modelo BIM la trayectoria física de la acometida en media tensión, coherente con la ubicación de subestación definida en el predimensionamiento y con las distancias de seguridad y profundidades de enterramiento exigidas.',
    requisitos: [
      'Ubicación de subestación definida (PB-01-01) confirmada en el modelo',
      'Levantamiento topográfico o planta de urbanismo vinculada',
      'Nivel de tensión de la red MT confirmado con el operador de red',
      'Norma de acometidas del operador de red de la zona',
    ],
    procedimiento: [
      'Vincular el plano de urbanismo o topografía como referencia de fondo (Insertar > Vincular CAD).',
      'Confirmar el nivel de tensión de la red MT, porque de él dependen las distancias de seguridad y la señalización aplicables a todo el trazado.',
      'Crear o seleccionar el sistema eléctrico "Media tensión" en la categoría Conductores eléctricos.',
      'Trazar el recorrido del cable de MT desde el punto de conexión indicado por el operador de red hasta la celda de llegada de la subestación.',
      'Asignar el tipo de conductor y el parámetro de tensión nominal correspondiente a MT.',
      'Verificar en las vistas de sección la profundidad de enterramiento y la separación respecto a redes de otras disciplinas, especialmente en cruces de vías y zonas duras.',
      'Confirmar que el trazado respeta la zona de servidumbre y las distancias de seguridad a construcciones cuando discurre por espacio público o cerca de edificaciones.',
      'Verificar que el recorrido mantenga la separación mínima frente a redes de gas y agua, y que los cruces se resuelvan con la protección mecánica prevista.',
      'Marcar los puntos de señalización y las cintas de prevención del trazado enterrado, que forman parte de la instalación y no solo del plano.',
    ],
    resultadoEsperado: 'Trazado continuo de la red de media tensión modelado en Revit, desde el punto de conexión hasta la subestación, con el tipo de conductor, la tensión nominal, la profundidad de enterramiento y las separaciones a otras redes resueltas.',
    criteriosVerificacion: [
      'El trazado de MT no presenta interrupciones entre el punto de conexión y la subestación.',
      'El parámetro de tensión nominal está asignado en todos los tramos del sistema.',
      'El trazado no cruza en planta ninguna red de otra disciplina sin punto de cruce validado.',
      'La profundidad de enterramiento indicada en las secciones es consistente en todo el recorrido.',
      'El trazado respeta la zona de servidumbre y las distancias de seguridad a construcciones vecinas.',
      'Los puntos de señalización del trazado enterrado están indicados en el modelo.',
    ],
    notasIngenieria: [
      notaNorma(
        'La acometida es una instalación objeto del RETIE y tiene su propio título de requisitos; el trazado modelado debe ser consistente con ellos y con la norma de acometidas del operador de red de la zona, que puede ser más exigente.',
        REF.ACOMETIDAS,
      ),
      notaNormaVerificar(
        'Las distancias mínimas de seguridad de una red de media tensión respecto a construcciones dependen del nivel de tensión y de la situación (fachada, ventana, cubierta transitable). Verificar el valor aplicable antes de fijar el trazado definitivo cerca de edificaciones.',
        REF.DISTANCIAS_CONSTRUCCIONES,
      ),
      notaNorma(
        'Los seccionadores, cortacircuitos e interruptores de media tensión asociados al punto de conexión tienen requisitos de instalación propios en el RETIE.',
        REF.EQUIPOS_MEDIA_TENSION,
      ),
      notaNorma(
        'El punto de conexión, el tipo de acometida y el esquema de medida los define la norma del operador de red, no el proyectista. En territorio de Enel Colombia eso está en el capítulo de acometidas eléctricas de Likinormas; en otra región, en la norma del operador que atienda el proyecto.',
        REF.LK_GENERALIDADES_ACOMETIDAS,
      ),
      notaNorma(
        'La acometida tiene sección propia en la NTC 2050, con requisitos de calibre, número de acometidas por edificación y medios de desconexión que el RETIE no reproduce.',
        REF.NTC_ACOMETIDAS,
      ),
    ],
    tipsRevit: [
      'Usa la categoría "Conductores eléctricos" con el sistema "Cable Tray" o "Conduit" según se modele ducto o cable directamente enterrado.',
      'Activa una vista de sección a lo largo del trazado para revisar cruces con otras redes antes de fijar la cota de enterramiento.',
      'Modela la franja de servidumbre como un sólido genérico a lo largo del trazado: cualquier elemento de otra disciplina que la invada aparecerá en la comprobación de interferencias en vez de descubrirse en la revisión del operador de red.',
      'Usa "Copiar/Monitorear" en la pestaña Colaborar para heredar el punto de conexión del vínculo de urbanismo y evitar desfases de coordenadas.',
    ],
  },
  {
    plantillaId: 'PB-02-02',
    nombreOriginal: 'Modelar redes de baja tensión',
    nombre: 'Modelar la red de distribución en baja tensión desde la subestación hasta los tableros de cada bloque',
    grupo: '02-modelado',
    subgrupo: 'Distribución BT',
    categoria: 'Acometidas',
    disciplina: 'Eléctrica',
    dificultad: 3,
    horasEstimadas: 10,
    prioridad: 'Alta',
    dependeDe: ['PB-02-01'],
    guiaIds: ['M5.2', 'M2.1'],
    descripcion: 'Modelado de los circuitos alimentadores en baja tensión que distribuyen la energía desde el tablero general de la subestación hasta los tableros de distribución de cada bloque o torre.',
    objetivo: 'Dejar representada en el modelo la topología de distribución en BT que servirá de base para el cálculo de circuitos, la selección de protecciones y la documentación de planos.',
    requisitos: [
      'Red de media tensión y subestación modeladas (PB-02-01)',
      'Listado de tableros generales por bloque definido',
      'Capacidad del transformador preliminar disponible (PB-01-04)',
      'Régimen de conexión a tierra (RCT) adoptado para el proyecto',
    ],
    procedimiento: [
      'Ubicar el tablero general de baja tensión (TGBT) en la subestación dentro del modelo.',
      'Confirmar el régimen de conexión a tierra adoptado (TN-S, TT u otro): de él depende si el alimentador lleva conductor de protección independiente del neutro, y por tanto su número de conductores.',
      'Crear el sistema eléctrico de alimentadores en BT desde el TGBT hacia cada tablero de bloque.',
      'Trazar el recorrido físico de cada alimentador siguiendo las rutas de ductos previstas en el predimensionamiento (PB-01-03).',
      'Asignar calibre y tipo de conductor provisional a cada alimentador según la carga estimada del bloque, dejando constancia de que el calibre definitivo sale del cálculo por capacidad de corriente, caída de tensión y cortocircuito.',
      'Verificar que cada tablero de bloque quede conectado a un único alimentador de origen sin bucles.',
      'Comprobar que cada alimentador tenga su protección contra sobrecorriente en el origen y que quede reflejada en el tablero de partida.',
      'Revisar en 3D que los alimentadores no interfieran con elementos estructurales del vínculo arquitectónico.',
    ],
    resultadoEsperado: 'Alimentadores de baja tensión modelados entre el TGBT de subestación y los tableros de cada bloque, con calibres provisionales, conductor de protección coherente con el RCT y protección de origen asignada, sin interferencias con la estructura.',
    criteriosVerificacion: [
      'Cada tablero de bloque tiene un único alimentador de origen conectado.',
      'Todos los tramos de alimentador tienen calibre y tipo de conductor asignado.',
      'El número de conductores por alimentador es coherente con el régimen de conexión a tierra adoptado.',
      'Cada alimentador tiene una protección contra sobrecorriente asignada en su tablero de origen.',
      'No existen bucles ni tramos huérfanos en el sistema de alimentadores.',
      'La revisión 3D no muestra interferencias entre alimentadores y elementos estructurales.',
    ],
    notasIngenieria: [
      notaNorma(
        'El régimen de conexión a tierra del proyecto es una decisión de diseño con título propio en el RETIE y condiciona la composición del alimentador: separar o no el neutro del conductor de protección cambia el número de conductores de cada tramo modelado.',
        REF.RCT,
      ),
      notaNormaVerificar(
        'Todo alimentador debe quedar protegido contra sobrecorrientes en su origen. La calibración de la protección depende del cálculo de cargas y de la coordinación con las protecciones aguas abajo; confirmar los valores con la memoria de diseño antes de cerrar los tableros.',
        REF.SOBRECORRIENTES,
      ),
      notaNormaVerificar(
        'El calibre definitivo no se elige por la carga estimada del bloque: resulta de la capacidad de corriente del conductor —con corrección por temperatura y por agrupamiento—, de la caída de tensión admisible y de la corriente de cortocircuito. La tabla de capacidad de corriente es la del Art. 310-15 de la NTC 2050.',
        REF.NTC_AMPACIDAD,
      ),
      notaNormaVerificar(
        'El neutro del alimentador no se dimensiona igual que las fases: la NTC 2050 permite reducirlo aplicando factores de demanda sobre la carga desbalanceada máxima, salvo en las cargas que la norma excluye. En vivienda esto cambia el calibre del alimentador de bloque.',
        REF.NTC_NEUTRO_ALIMENTADOR,
      ),
      notaNormaVerificar(
        'El conductor de puesta a tierra de equipos que acompaña al alimentador se dimensiona por la capacidad del dispositivo de protección aguas arriba, no por el calibre de las fases.',
        REF.NTC_CALIBRE_TIERRA_EQUIPOS,
      ),
      notaNormaVerificar(
        'La carga del alimentador de un bloque de vivienda se puede calcular por el método general o por el método opcional para viviendas multifamiliares, que aplica factores de demanda distintos. Fijar cuál se usó en la memoria antes de dimensionar: los dos son válidos y dan resultados diferentes.',
        REF.NTC_OPCIONAL_MULTIFAMILIAR,
      ),
    ],
    tipsRevit: [
      'Usa "Sistema eléctrico" (Electrical System) para agrupar los alimentadores por tablero de origen y facilitar su identificación en tablas.',
      'Filtra la vista 3D por el parámetro "Sistema eléctrico" para aislar únicamente los alimentadores de BT durante la revisión de interferencias.',
      'Usa el parámetro "Longitud" del sistema eléctrico como insumo directo del cálculo de caída de tensión: es el dato que más se equivoca cuando se estima a mano sobre plano.',
      'Crea un parámetro compartido para el calibre calculado, distinto del provisional, para poder auditar en una tabla qué tramos siguen con el valor estimado.',
    ],
  },
  {
    plantillaId: 'PB-02-03',
    nombreOriginal: 'Propuesta de salidas',
    nombre: 'Proponer la ubicación de las salidas de tomacorriente y fuerza en la planta arquitectónica',
    grupo: '02-modelado',
    subgrupo: 'Tomacorrientes y fuerza',
    categoria: 'Tomacorrientes',
    disciplina: 'Eléctrica',
    dificultad: 2,
    horasEstimadas: 8,
    prioridad: 'Alta',
    dependeDe: [],
    guiaIds: ['M5.5', 'M2.5'],
    descripcion: 'Definición inicial, sobre la planta arquitectónica vinculada, de la cantidad y ubicación aproximada de las salidas de tomacorriente normales y de fuerza requeridas por espacio.',
    objetivo: 'Establecer una propuesta de ubicación de salidas eléctricas que sirva de base para el modelado detallado de tomacorrientes, ya diferenciando desde el inicio los espacios que exigen protección diferencial y circuito dedicado.',
    requisitos: [
      'Planta arquitectónica vinculada y niveles verificados (PB-01-10)',
      'Programa de áreas o usos de cada espacio disponible',
      'Criterio de cantidad mínima de salidas por espacio del código eléctrico aplicable',
    ],
    procedimiento: [
      'Revisar la planta arquitectónica vinculada e identificar el uso de cada espacio (habitación, cocina, baño, zona común, cuarto técnico, exterior).',
      'Marcar los espacios húmedos o a la intemperie —baños, cocinas, zonas de lavado, terrazas, exteriores— porque sus tomas exigen protección diferencial y, según el caso, grado de protección reforzado.',
      'Identificar los electrodomésticos y equipos de alta demanda que requieren circuito dedicado, en lugar de repartirlos en los circuitos generales.',
      'Colocar familias de tomacorriente tipo "marcador" o placeholder en cada punto propuesto, usando la categoría Dispositivos eléctricos.',
      'Asignar a cada marcador los parámetros de tipo de salida (normal, fuerza, especial), de si requiere protección diferencial y de si pertenece a un circuito dedicado.',
      'Contrastar la cantidad de salidas por espacio contra el criterio mínimo del código eléctrico aplicable y contra el programa arquitectónico.',
      'Registrar en una tabla de planificación el conteo de salidas propuestas por nivel, uso y tipo.',
    ],
    resultadoEsperado: 'Propuesta de ubicación de salidas de tomacorriente y fuerza colocada sobre la planta arquitectónica, con conteo por nivel y tipo, y con los espacios que exigen protección diferencial o circuito dedicado ya identificados.',
    criteriosVerificacion: [
      'Todos los espacios habitables tienen al menos una salida propuesta.',
      'Cada marcador de salida tiene asignado el parámetro de tipo (normal, fuerza, especial).',
      'Las salidas de espacios húmedos y exteriores están marcadas como con protección diferencial.',
      'Los equipos de alta demanda identificados tienen su salida marcada como circuito dedicado.',
      'La tabla de planificación refleja el conteo real de marcadores colocados en el modelo.',
    ],
    notasIngenieria: [
      notaNormaVerificar(
        'La cantidad mínima de salidas por espacio y su distribución la fija el código eléctrico aplicable, no el criterio del modelador. Esta propuesta es un punto de partida sujeto a validación por el diseñador.',
        REF.INSTALACIONES_BASICAS,
      ),
      notaNormaVerificar(
        'En unidades de vivienda la regla es concreta: ningún punto del perímetro de pared de salas, alcobas y espacios similares puede quedar a más de la distancia reglada de un tomacorriente, y los mesones de cocina tienen su propia regla de separación. Está en el Art. 210-52 de la NTC 2050, no en el RETIE.',
        REF.NTC_TOMAS_VIVIENDA,
      ),
      notaNorma(
        'Baños, cocinas (mesón), exteriores, sótanos, garajes y zonas cercanas a lavaderos exigen tomacorrientes protegidos con interruptor de falla a tierra. El listado de lugares está en el Art. 210-8 de la NTC 2050: revisarlo espacio por espacio antes de repartir salidas.',
        REF.NTC_GFCI,
      ),
      notaNormaVerificar(
        'Los equipos de aire acondicionado, calefacción y congelador tienen salida propia reglada: no cuelgan de un circuito de tomas de uso general.',
        REF.NTC_TOMAS_EQUIPOS,
      ),
      notaNorma(
        'La protección contra falla de aislamiento mediante dispositivos de corriente diferencial residual es obligatoria en los casos que fija el RETIE, típicamente asociados a zonas húmedas y a tomas accesibles. Marcarlo desde la propuesta evita rehacer circuitos después.',
        REF.PROTECCION_AISLAMIENTO,
      ),
      notaNorma(
        'Los tomacorrientes deben cumplir requisitos de instalación propios —altura, grado de protección, polo a tierra y configuración de clavija— definidos en el artículo de clavijas y tomacorrientes del RETIE.',
        REF.TOMACORRIENTES,
      ),
    ],
    tipsRevit: [
      'Crea una familia de marcador liviana (sin geometría 3D compleja) para la propuesta inicial y así evitar peso de archivo innecesario.',
      'Añade al marcador un parámetro de tipo "Requiere DDR" desde la propuesta: al agrupar la tabla por ese parámetro obtienes de inmediato cuántos circuitos diferenciales necesitará el tablero.',
      'Usa una tabla de planificación de "Dispositivos eléctricos" agrupada por nivel y tipo para llevar el conteo mientras propones las salidas.',
      'Aplica un filtro de vista por parámetro de tipo de salida para revisar visualmente la distribución de normales vs. fuerza en la planta.',
    ],
  },
  {
    plantillaId: 'PB-02-04',
    nombreOriginal: 'Modelar redes de servicios comunes',
    nombre: 'Modelar las redes eléctricas de alimentación de las zonas de servicios comunes del proyecto',
    grupo: '02-modelado',
    subgrupo: 'Distribución BT',
    categoria: 'Modelado',
    disciplina: 'Eléctrica',
    dificultad: 3,
    horasEstimadas: 8,
    prioridad: 'Media',
    dependeDe: ['PB-02-02'],
    guiaIds: ['M2.1', 'M5.2'],
    descripcion: 'Modelado de los circuitos que alimentan zonas comunes como parqueaderos, salones sociales, cuartos de bombas, portería y demás áreas compartidas del proyecto.',
    objetivo: 'Dejar completamente trazadas y conectadas las redes eléctricas de las zonas de uso común, diferenciadas de los circuitos privativos y con los servicios de seguridad separados de los servicios normales.',
    requisitos: [
      'Alimentadores de baja tensión modelados (PB-02-02)',
      'Listado de zonas comunes del proyecto arquitectónico',
      'Identificación de las cargas que pertenecen a servicios de seguridad',
    ],
    procedimiento: [
      'Identificar en la planta arquitectónica vinculada todas las zonas clasificadas como servicios comunes.',
      'Separar de esa lista las cargas que son servicios de seguridad —bomba contra incendio, iluminación de evacuación, presurización de escaleras, ascensor de bomberos— porque no pueden compartir circuito con los servicios normales.',
      'Crear el tablero de servicios comunes (o los tableros por zona) dentro del modelo eléctrico.',
      'Crear un tablero o sección independiente para los servicios de seguridad, alimentado desde su fuente de respaldo.',
      'Trazar los circuitos desde cada tablero hacia sus cargas (bombas, portón, iluminación exterior común, etc.).',
      'Asignar el sistema eléctrico correspondiente a cada circuito para diferenciarlo de los circuitos privativos y de los de seguridad.',
      'Verificar que los tableros de zonas comunes accesibles al público queden con cerradura o en recinto restringido, no expuestos.',
      'Verificar en una tabla de planificación que ninguna carga de zona común quede conectada a un tablero privativo y que ninguna carga de seguridad quede en el tablero normal.',
    ],
    resultadoEsperado: 'Redes eléctricas de servicios comunes modeladas y conectadas a su tablero correspondiente, diferenciadas de los circuitos privativos y con los servicios de seguridad en un tablero independiente respaldado.',
    criteriosVerificacion: [
      'Todas las cargas identificadas como servicios comunes están conectadas al tablero de servicios comunes.',
      'Ningún circuito de zona común aparece conectado a un tablero privativo.',
      'Las cargas de servicios de seguridad están en un tablero o sección independiente de los servicios normales.',
      'Los tableros ubicados en zonas de acceso público están en recinto restringido o con cerradura.',
      'Cada circuito de servicios comunes tiene asignado su sistema eléctrico.',
    ],
    notasIngenieria: [
      notaNorma(
        'Los sistemas de emergencia deben ser independientes de los sistemas normales y contar con su fuente de respaldo; agruparlos en el tablero de servicios comunes por comodidad de modelado incumple esa separación.',
        REF.SISTEMAS_EMERGENCIA,
      ),
      notaNorma(
        'Los tableros de distribución instalados en espacios de uso público tienen requisitos específicos de accesibilidad restringida y protección contra manipulación en el RETIE.',
        REF.TABLEROS_USO_PUBLICO,
      ),
      notaNorma(
        'Los circuitos ramales que alimentan zonas comunes de un edificio multifamiliar tienen artículo propio en la NTC 2050: no pueden derivarse del circuito de una unidad de vivienda y deben alimentarse desde el tablero de servicios comunes.',
        REF.NTC_RAMALES_ZONAS_COMUNES,
      ),
      notaCriterio(
        'La separación de circuitos comunes y privativos es relevante para la facturación de energía por copropiedad; confirmar el criterio de agrupación con el diseño de conjunto antes de cerrar el modelado.',
      ),
    ],
    tipsRevit: [
      'Usa el parámetro compartido "Tipo de circuito" (común / privativo / seguridad) para poder filtrar y auditar la separación desde una tabla de planificación.',
      'Agrupa los circuitos de servicios comunes en un "Sistema eléctrico" independiente por tablero para simplificar la lectura del diagrama unifilar.',
      'Crea un filtro de vista que pinte en rojo todo circuito de seguridad: un circuito de emergencia conectado por error al tablero normal salta a la vista en la planta en lugar de esconderse en la tabla.',
      'Verifica con el comando "Verificar sistema" (Check Circuit) que cada circuito común cierre correctamente antes de continuar con la documentación.',
    ],
  },
  {
    plantillaId: 'PB-02-05',
    nombreOriginal: 'Modelar iluminación y tomas foso de ascensor',
    nombre: 'Modelar la iluminación y las tomas eléctricas del foso del ascensor',
    grupo: '02-modelado',
    subgrupo: 'Iluminación',
    categoria: 'Iluminación',
    disciplina: 'Eléctrica',
    dificultad: 2,
    horasEstimadas: 3,
    prioridad: 'Media',
    dependeDe: [],
    guiaIds: ['M5.4'],
    descripcion: 'Modelado de la luminaria y el tomacorriente de mantenimiento requeridos dentro del foso de ascensor, conforme a las dimensiones del foso definidas por el proveedor del equipo y a los requisitos del RETIE para instalaciones de ascensores.',
    objetivo: 'Garantizar que el foso de ascensor cuente con iluminación, toma de mantenimiento y accionamiento modelados conforme a los requisitos del fabricante y de la norma.',
    requisitos: [
      'Ficha técnica del ascensor con dimensiones del foso',
      'Modelo arquitectónico del foso vinculado y verificado',
      'Definición del tablero que alimenta el cuarto de máquinas',
    ],
    procedimiento: [
      'Revisar la ficha técnica del ascensor para confirmar la posición requerida de luminaria, toma e interruptor en el foso.',
      'Colocar la familia de luminaria de foso en la posición indicada, hospedada en el muro o losa del foso.',
      'Colocar la familia de tomacorriente de mantenimiento junto al acceso al foso, con protección diferencial por tratarse de un recinto húmedo y de acceso ocasional.',
      'Ubicar el interruptor de la iluminación del foso de modo que sea accionable desde el acceso, sin necesidad de bajar al foso a oscuras.',
      'Crear el circuito que alimenta la luminaria y la toma del foso desde el tablero del cuarto de máquinas.',
      'Verificar que el circuito del foso sea independiente del circuito de fuerza del ascensor: la maniobra de mantenimiento debe poder desenergizar el equipo sin quedarse sin luz.',
      'Verificar en una vista de sección que la altura de montaje de todos los elementos cumpla lo indicado por el fabricante y quede fuera del recorrido de la cabina y del contrapeso.',
    ],
    resultadoEsperado: 'Luminaria, toma de mantenimiento e interruptor del foso de ascensor modelados en la posición y altura indicadas por el fabricante, en circuito independiente del de fuerza del ascensor.',
    criteriosVerificacion: [
      'La luminaria del foso está hospedada en el elemento correcto (muro o losa del foso).',
      'La toma de mantenimiento está ubicada junto al acceso al foso según la ficha técnica y tiene protección diferencial.',
      'El interruptor de iluminación es accionable desde el acceso al foso.',
      'El circuito del foso es independiente del circuito de fuerza del ascensor.',
      'La altura de montaje verificada en sección coincide con la especificación del fabricante y no invade el recorrido de cabina ni contrapeso.',
    ],
    notasIngenieria: [
      notaNorma(
        'Las instalaciones eléctricas de ascensores, escaleras y andenes móviles son equipos especiales con requisitos propios en el RETIE, incluidos los medios de desconexión y la iluminación de foso y cuarto de máquinas.',
        REF.ASCENSORES,
      ),
      notaNorma(
        'La NTC 2050 dedica la Sección 620 a ascensores y montacargas: alimentación del cuarto de máquinas, alumbrado y tomacorriente del foso, y medios de desconexión. Es la sección que hay que abrir para modelar el foso, no el reglamento.',
        REF.NTC_ASCENSORES,
      ),
      notaNormaVerificar(
        'El foso es un recinto con riesgo de humedad y acceso ocasional de personal de mantenimiento: la toma exige protección contra falla de aislamiento. Confirmar el esquema exacto con el diseño y con la ficha técnica del ascensor.',
        REF.PROTECCION_AISLAMIENTO,
      ),
    ],
    tipsRevit: [
      'Usa una familia de luminaria hospedada en cara (face-based) para que se ajuste automáticamente a la geometría del foso si esta cambia.',
      'Activa la vista de sección "Foso de ascensor" desde el vínculo arquitectónico para validar alturas sin necesidad de crear una vista nueva.',
      'Modela el gálibo de cabina y contrapeso como un sólido genérico dentro del foso e inclúyelo en la detección de interferencias: es la forma fiable de comprobar que la luminaria no queda en el recorrido.',
      'Verifica el parámetro "Nivel de referencia" de la luminaria y la toma para asegurar que midan la altura desde el fondo real del foso y no desde el nivel del piso del edificio.',
    ],
  },
  {
    plantillaId: 'PB-02-06',
    nombreOriginal: 'Modelar vertical tomas de gabinetes',
    nombre: 'Modelar el ramal vertical de alimentación a las tomas de los gabinetes de medidores',
    grupo: '02-modelado',
    subgrupo: 'Tomacorrientes y fuerza',
    categoria: 'Tomacorrientes',
    disciplina: 'Eléctrica',
    dificultad: 3,
    horasEstimadas: 6,
    prioridad: 'Media',
    dependeDe: ['PB-02-02'],
    guiaIds: ['M5.5', 'M2.5'],
    descripcion: 'Modelado del ducto vertical (shaft eléctrico) y los circuitos que alimentan las tomas ubicadas en los gabinetes de medidores de cada piso.',
    objetivo: 'Representar el recorrido vertical completo, piso a piso, que alimenta las tomas de los gabinetes de medidores desde su origen, con los pasos de losa sellados y el porcentaje de ocupación respetado.',
    requisitos: [
      'Alimentadores de baja tensión modelados (PB-02-02)',
      'Ubicación del shaft eléctrico confirmada en todos los niveles',
      'Resistencia al fuego exigida a las losas que atraviesa el shaft',
    ],
    procedimiento: [
      'Verificar en el modelo vinculado que el shaft eléctrico está alineado en todos los niveles del edificio.',
      'Crear el circuito vertical de alimentación a tomas de gabinetes usando una vista de sección o alzado que abarque todos los pisos.',
      'Colocar la toma de cada gabinete de medidores en cada nivel y conectarla al ramal vertical correspondiente.',
      'Asignar el calibre de conductor del ramal vertical según el número de pisos servidos y verificar el porcentaje de ocupación de la canalización.',
      'Modelar el sello cortafuego en cada paso de losa del shaft: el ducto vertical atraviesa un elemento con resistencia al fuego en cada piso y debe restituirla.',
      'Prever los soportes del tramo vertical, cuya separación la fija el tipo de canalización y no puede quedar librada al montaje.',
      'Revisar en 3D que el ramal vertical no presente desalineaciones entre niveles.',
      'Confirmar en una tabla de planificación que cada gabinete de medidores tiene su toma conectada.',
    ],
    resultadoEsperado: 'Ramal vertical de alimentación a tomas de gabinetes modelado y alineado en todos los niveles, con cada toma conectada, los pasos de losa sellados y los soportes previstos.',
    criteriosVerificacion: [
      'El ramal vertical está alineado (sin desfases en planta) en todos los niveles del shaft.',
      'Cada gabinete de medidores tiene su toma conectada al ramal vertical.',
      'El calibre del ramal vertical está asignado según el número de pisos servidos y respeta el porcentaje de ocupación.',
      'Cada paso de losa del shaft tiene su sello cortafuego modelado.',
      'No hay tramos del ramal vertical desconectados entre niveles consecutivos.',
    ],
    notasIngenieria: [
      notaNorma(
        'Un ducto vertical atraviesa una losa con resistencia al fuego en cada piso: cada paso debe restituirse con sello cortafuego, y modelarlo desde el inicio evita descubrirlo en la inspección de certificación.',
        REF.SELLOS_CORTAFUEGO,
      ),
      notaNorma(
        'El sellado no es solo del ducto: la NTC 2050 exige restituir la resistencia al fuego en todo paso de canalización por elementos cortafuego, para que la instalación no se vuelva un camino de propagación entre pisos.',
        REF.NTC_PROPAGACION_FUEGO,
      ),
      notaNormaVerificar(
        'El tablero general de acometidas y su ramal vertical siguen la ficha del operador de red en cuanto a barrajes, espacio y accesibilidad; conviene contrastarla antes de fijar la sección del ducto.',
        REF.LK_TABLERO_GENERAL_ACOMETIDAS,
      ),
      notaNormaVerificar(
        'La separación entre soportes y el porcentaje máximo de ocupación de la canalización vertical están reglados; verificar los valores aplicables al tipo de canalización elegido antes de cerrar el modelado.',
        REF.CANALIZACIONES,
      ),
    ],
    tipsRevit: [
      'Usa una vista de alzado o sección "Shaft eléctrico" que corte todos los niveles para modelar el ramal vertical de una sola vez.',
      'Habilita "Restricciones de nivel" (Base Level / Top Level) en el conducto vertical para que se ajuste automáticamente si cambia la altura de piso a piso.',
      'Crea una familia de sello cortafuego hospedada en cara y colócala en cada intersección ducto-losa: así los sellos se cuentan solos en la tabla de cantidades en lugar de contarse a mano en el plano.',
      'Usa el comando "Alinear" con la opción de alineación múltiple para verificar que los tramos verticales de cada piso queden centrados en el shaft.',
    ],
  },
  {
    plantillaId: 'PB-02-07',
    nombreOriginal: 'Caja de puesta a tierra en armarios',
    nombre: 'Modelar la caja de puesta a tierra en los armarios de medidores',
    grupo: '02-modelado',
    subgrupo: 'Puesta a tierra y apantallamiento',
    categoria: 'Sistemas Especiales',
    disciplina: 'Eléctrica',
    dificultad: 2,
    horasEstimadas: 3,
    prioridad: 'Alta',
    dependeDe: [],
    guiaIds: ['M5.6'],
    descripcion: 'Colocación en el modelo de la caja de puesta a tierra asociada a cada armario o cuarto de medidores, como punto de conexión y registro del sistema de puesta a tierra.',
    objetivo: 'Dejar modelada la caja de puesta a tierra de cada armario de medidores en una posición registrable y accesible, conectada al sistema de puesta a tierra del proyecto.',
    requisitos: [
      'Ubicación de armarios de medidores confirmada en el modelo arquitectónico',
      'Definición del sistema de puesta a tierra del proyecto',
      'Criterio de conexión equipotencial adoptado',
    ],
    procedimiento: [
      'Ubicar cada armario de medidores en el modelo arquitectónico vinculado.',
      'Colocar la familia de caja de puesta a tierra junto a cada armario, respetando la distancia mínima al piso terminado indicada en el diseño.',
      'Verificar que la caja quede accesible y registrable: es el punto donde se miden la continuidad y la resistencia de puesta a tierra durante la inspección y el mantenimiento.',
      'Conectar la caja de puesta a tierra al conductor de tierra del armario mediante el sistema eléctrico de puesta a tierra.',
      'Comprobar que el conductor de puesta a tierra no quede interrumpido por ningún dispositivo de maniobra o protección a lo largo de su recorrido.',
      'Confirmar que los elementos metálicos del armario queden unidos al mismo punto de puesta a tierra, cerrando la equipotencialidad del conjunto.',
      'Verificar en una tabla de planificación que exista una caja de puesta a tierra por cada armario de medidores modelado.',
    ],
    resultadoEsperado: 'Caja de puesta a tierra modelada junto a cada armario de medidores, accesible para medición, conectada al sistema de puesta a tierra y con las partes metálicas del armario equipotencializadas.',
    criteriosVerificacion: [
      'Existe una caja de puesta a tierra por cada armario de medidores del modelo.',
      'Cada caja está conectada al conductor de puesta a tierra del armario correspondiente.',
      'La caja queda accesible y registrable para las mediciones de puesta a tierra.',
      'El conductor de puesta a tierra no atraviesa ningún dispositivo de maniobra o protección.',
      'La posición de la caja respeta la distancia al piso terminado definida en el diseño.',
    ],
    notasIngenieria: [
      notaNorma(
        'Las cajas de inspección son componentes del sistema de puesta a tierra y su función es permitir la medición y el mantenimiento; una caja modelada en un punto inaccesible cumple en el plano pero no en obra.',
        REF.SPT_COMPONENTES,
      ),
      notaNorma(
        'La instalación del electrodo de puesta a tierra del sistema —profundidad, unión con otros electrodos y accesibilidad de la conexión— está reglada en el Art. 250-81 de la NTC 2050.',
        REF.NTC_ELECTRODO,
      ),
      notaNormaVerificar(
        'El calibre del conductor del electrodo de puesta a tierra se toma de la tabla del Art. 250-94, en función del calibre de los conductores de acometida; no se elige por criterio.',
        REF.NTC_CALIBRE_ELECTRODO,
      ),
      notaNorma(
        'El conductor de puesta a tierra no puede llevar dispositivos de maniobra ni de protección que puedan interrumpirlo: la continuidad del sistema es un requisito general de la puesta a tierra.',
        REF.SPT_GENERAL,
      ),
    ],
    tipsRevit: [
      'Modela la caja de puesta a tierra como familia basada en el suelo (hospedada en Piso) para que su cota se ajuste automáticamente al nivel del proyecto.',
      'Usa el sistema "Conductor de puesta a tierra" dentro de Sistemas eléctricos para diferenciar visualmente esta red de los circuitos de fuerza.',
      'Agrega una tabla de planificación filtrada por la familia de caja de puesta a tierra para auditar rápidamente que no falte ninguna junto a un armario.',
    ],
  },
  {
    plantillaId: 'PB-02-08',
    nombreOriginal: 'Malla de puesta a tierra',
    nombre: 'Modelar la malla de puesta a tierra de la subestación',
    grupo: '02-modelado',
    subgrupo: 'Puesta a tierra y apantallamiento',
    categoria: 'Sistemas Especiales',
    disciplina: 'Eléctrica',
    dificultad: 3,
    horasEstimadas: 10,
    prioridad: 'Alta',
    dependeDe: ['PB-01-01'],
    guiaIds: ['M5.6'],
    descripcion: 'Modelado de la malla de puesta a tierra de la subestación, incluyendo conductores de la malla, varillas de puesta a tierra, cajas de inspección y puntos de conexión a equipos.',
    objetivo: 'Representar en el modelo la malla de puesta a tierra de la subestación como base para la documentación de planos de SPT, con los puntos de medición previstos y todos los equipos conectados.',
    requisitos: [
      'Ubicación y dimensiones de la subestación definidas (PB-01-01)',
      'Estudio de resistividad del terreno del proyecto',
      'Diseño de la malla con su retículo, calibre y número de varillas',
    ],
    procedimiento: [
      'Partir del diseño de la malla entregado por el ingeniero: el retículo, el calibre del conductor y el número de varillas salen del estudio de resistividad, no se proponen en el modelado.',
      'Trazar el perímetro de la malla de puesta a tierra en planta, dentro del área de la subestación.',
      'Modelar los conductores de la malla como sistema eléctrico de puesta a tierra, respetando el retículo de diseño.',
      'Colocar las varillas de puesta a tierra en los puntos de cruce o extremos definidos en el diseño.',
      'Ubicar las cajas de inspección que permitirán medir la resistencia de puesta a tierra tras la construcción y durante el mantenimiento.',
      'Conectar cada equipo de la subestación (transformador, tablero general, celdas, puertas y estructuras metálicas) a la malla mediante bajantes de puesta a tierra.',
      'Verificar que la malla se conecte al sistema de puesta a tierra general de la edificación en un único sistema equipotencial, en lugar de quedar como una tierra aislada.',
      'Verificar en 3D que todos los equipos de la subestación tengan al menos una conexión a la malla.',
    ],
    resultadoEsperado: 'Malla de puesta a tierra de la subestación modelada con sus varillas, conductores y cajas de inspección, con todos los equipos y elementos metálicos conectados mediante bajantes y unida al sistema equipotencial de la edificación.',
    criteriosVerificacion: [
      'La malla de puesta a tierra forma un circuito cerrado sin tramos huérfanos.',
      'Todos los equipos principales y las estructuras metálicas de la subestación tienen al menos una conexión a la malla.',
      'Las varillas de puesta a tierra están ubicadas en los puntos definidos en el diseño.',
      'Existen cajas de inspección que permiten medir la resistencia de puesta a tierra.',
      'La malla está integrada al sistema equipotencial general y no queda como tierra aislada.',
      'El retículo y el calibre modelados coinciden con el diseño derivado del estudio de resistividad.',
    ],
    notasIngenieria: [
      notaNormaVerificar(
        'El valor máximo de resistencia de puesta a tierra aplicable depende del tipo de instalación y está tabulado en el RETIE; no es un dato que se asuma durante el modelado ni que se derive del retículo dibujado. Confirmarlo contra el diseño y el estudio de resistividad del proyecto.',
        REF.SPT_RESISTENCIA,
      ),
      notaNormaVerificar(
        'Los electrodos fabricados (varillas, tubos, placas) tienen material, longitud mínima y separación reglados en el Art. 250-83 de la NTC 2050; el Art. 250-84 fija qué hacer cuando un solo electrodo no alcanza el valor de resistencia esperado.',
        REF.NTC_ELECTRODOS_FABRICADOS,
      ),
      notaNorma(
        'La resistencia de puesta a tierra debe medirse con métodos y equipos definidos por la norma una vez construida la malla; las cajas de inspección modeladas son las que hacen posible esa medición.',
        REF.SPT_MEDICIONES,
      ),
      notaNorma(
        'Las puestas a tierra de una misma edificación deben interconectarse en un solo sistema equipotencial; dejar la malla de la subestación aislada del resto genera diferencias de potencial peligrosas.',
        REF.SPT_GENERAL,
      ),
    ],
    tipsRevit: [
      'Modela la malla de puesta a tierra como un sistema eléctrico independiente, distinto del sistema de conductores de fuerza, para poder aislarla en el diagrama unifilar.',
      'Usa una familia genérica basada en línea para las varillas de puesta a tierra y así facilitar su conteo en una tabla de planificación.',
      'Registra en un parámetro compartido de la malla el valor de resistencia objetivo del diseño y déjalo visible en el plano de SPT: es el dato que el inspector va a contrastar contra la medición en obra.',
      'Activa una vista 3D con caja de sección (Section Box) limitada al área de subestación para revisar visualmente que cada bajante llegue efectivamente a la malla.',
    ],
  },
  {
    plantillaId: 'PB-02-09',
    nombreOriginal: 'Creación de circuitos (uno por tipología)',
    nombre: 'Crear un circuito eléctrico representativo por cada tipología de unidad del proyecto',
    grupo: '02-modelado',
    subgrupo: 'Distribución BT',
    categoria: 'Tableros',
    disciplina: 'Eléctrica',
    dificultad: 3,
    horasEstimadas: 10,
    prioridad: 'Alta',
    dependeDe: ['PB-02-03'],
    guiaIds: ['M5.3'],
    descripcion: 'Creación, en el modelo, de un circuito eléctrico completo (tomas e iluminación conectadas a un panel) para cada tipología de apartamento o unidad definida en el proyecto arquitectónico, como base replicable para el resto de unidades iguales.',
    objetivo: 'Contar con un circuito modelado y verificado por cada tipología, que sirva de plantilla para replicar en las unidades restantes del mismo tipo, con la separación de circuitos y las protecciones ya correctas en el modelo tipo.',
    requisitos: [
      'Propuesta de salidas definida (PB-02-03)',
      'Listado de tipologías de unidad del proyecto arquitectónico',
      'Criterio de separación de circuitos y de carga máxima por circuito del diseño',
    ],
    procedimiento: [
      'Identificar en el modelo arquitectónico las tipologías de unidad distintas (por ejemplo, apartamento tipo A, tipo B).',
      'Seleccionar una unidad representativa de cada tipología en el modelo eléctrico.',
      'Separar los circuitos de iluminación de los de tomacorriente, y dejar en circuito propio las cargas identificadas como dedicadas en PB-02-03.',
      'Agrupar en circuitos protegidos por diferencial las salidas de zonas húmedas y exteriores marcadas en la propuesta.',
      'Crear el sistema eléctrico de fuerza o iluminación seleccionando las salidas de cada grupo y asignándolas a su circuito.',
      'Conectar cada circuito creado al panel de distribución correspondiente a esa unidad.',
      'Verificar en la tabla de planificación de paneles que cada circuito muestra la carga conectada y el número de salidas correcto, y que ninguno supera la carga máxima del criterio de diseño.',
      'Documentar el circuito tipo como referencia para la replicación en las demás unidades de la misma tipología.',
    ],
    resultadoEsperado: 'Un juego de circuitos completo y verificado por cada tipología de unidad, con iluminación y tomas separadas, cargas dedicadas aisladas y protección diferencial en las zonas que la exigen, listo como plantilla de replicación.',
    criteriosVerificacion: [
      'Existe al menos un circuito creado por cada tipología de unidad identificada.',
      'Los circuitos de iluminación están separados de los de tomacorriente.',
      'Las cargas marcadas como dedicadas en PB-02-03 están en circuito propio.',
      'Las salidas de zonas húmedas y exteriores están agrupadas en circuitos con protección diferencial.',
      'Cada circuito está conectado a un panel de distribución válido.',
      'La tabla de planificación del panel muestra la carga conectada del circuito sin valores en cero o vacíos.',
      'El número de salidas del circuito coincide con el número de salidas propuestas para esa unidad (PB-02-03).',
    ],
    notasIngenieria: [
      notaNormaVerificar(
        'La separación entre circuitos de iluminación, tomas y cargas dedicadas, y la carga máxima admisible por circuito, salen del diseño y del código eléctrico aplicable. Un error aquí se replica en todas las unidades de la tipología, así que conviene validarlo antes de copiar.',
        REF.INSTALACIONES_BASICAS,
      ),
      notaNormaVerificar(
        'La NTC 2050 fija los circuitos ramales obligatorios de una unidad de vivienda: al menos dos circuitos de 20 A para pequeños electrodomésticos (cocina y comedor), uno propio para lavandería y los dedicados de estufa y secadora. Esa es la base de la tipología, antes de repartir salidas.',
        REF.NTC_PEQUENOS_ELECTRO,
      ),
      notaNormaVerificar(
        'La carga permisible de un circuito ramal está limitada en función de su capacidad nominal: un circuito de tomas de uso general no admite cualquier número de salidas.',
        REF.NTC_CARGAS_PERMISIBLES,
      ),
      notaNorma(
        'Cada habitación de la vivienda tiene salidas de alumbrado obligatorias y control desde interruptor de pared reglado en el Art. 210-70; no basta con tomas.',
        REF.NTC_SALIDAS_ALUMBRADO,
      ),
      notaNorma(
        'Cada circuito ramal debe quedar protegido contra sobrecorrientes; el circuito tipo debe nacer ya con su protección asignada, no añadirla después de replicar.',
        REF.SOBRECORRIENTES,
      ),
      notaNorma(
        'Las salidas de zonas húmedas y exteriores requieren protección contra falla de aislamiento; agruparlas en el circuito tipo evita rehacer la distribución tras la replicación.',
        REF.PROTECCION_AISLAMIENTO,
      ),
    ],
    tipsRevit: [
      'Selecciona las salidas y usa el comando de creación de "Sistema eléctrico" (Power) desde la pestaña Sistemas para crear el circuito directamente.',
      'Usa la tabla de planificación de paneles (Panel Schedule) del tablero para revisar de inmediato la carga conectada tras crear el circuito.',
      'Verifica el circuito tipo por completo antes de replicar: un grupo de Revit copiado 40 veces convierte un error de un circuito en 40 correcciones manuales.',
      'Nombra el circuito con un identificador que incluya la tipología (por ejemplo "TIPO-A-C1") para facilitar su localización al momento de replicar en otras unidades.',
    ],
  },
  {
    plantillaId: 'PB-02-10',
    nombreOriginal: 'Ubicación de interruptores y salidas',
    nombre: 'Ubicar los interruptores (breakers) en los tableros y verificar su conexión con las salidas asociadas',
    grupo: '02-modelado',
    subgrupo: 'Distribución BT',
    categoria: 'Modelado',
    disciplina: 'Eléctrica',
    dificultad: 2,
    horasEstimadas: 6,
    prioridad: 'Alta',
    dependeDe: ['PB-02-09'],
    guiaIds: ['M5.3', 'M5.2'],
    descripcion: 'Verificación y ajuste, dentro de la tabla de planificación del panel, de la posición de cada interruptor (breaker), su correspondencia con las salidas conectadas al circuito y su rotulación.',
    objetivo: 'Asegurar que cada interruptor del tablero corresponda a un circuito con salidas conectadas, que su posición sea coherente con el balanceo de fases y que quede identificado con un rótulo trazable.',
    requisitos: [
      'Circuitos creados para al menos una tipología (PB-02-09)',
      'Panel de distribución modelado con sus fases definidas',
      'Criterio de rotulación de circuitos del proyecto',
    ],
    procedimiento: [
      'Abrir la tabla de planificación (Panel Schedule) del tablero a revisar.',
      'Verificar que cada circuito creado tenga un interruptor asignado en una posición del panel.',
      'Revisar la distribución de circuitos entre fases para evitar desbalanceo evidente.',
      'Confirmar en el modelo 3D que las salidas asociadas a cada interruptor corresponden al circuito correcto.',
      'Verificar que la capacidad nominal de cada interruptor sea coherente con el calibre del conductor que protege: el breaker protege al conductor, no solo a la carga.',
      'Confirmar que los circuitos con protección diferencial tengan efectivamente asignado un dispositivo diferencial y no solo un interruptor termomagnético.',
      'Revisar que cada circuito tenga un rótulo claro en el cuadro de cargas, que es la información con la que se opera y mantiene el tablero.',
      'Ajustar la posición de los interruptores en la tabla de planificación cuando se detecte un cruce de circuitos.',
    ],
    resultadoEsperado: 'Interruptores del tablero ubicados en posiciones correctas dentro del panel, con correspondencia verificada entre cada breaker, su conductor y sus salidas, y con el cuadro de cargas rotulado.',
    criteriosVerificacion: [
      'Cada circuito tiene un interruptor asignado a una posición válida del panel.',
      'No hay dos circuitos distintos asignados a la misma posición del panel.',
      'La capacidad de cada interruptor es coherente con el calibre del conductor que protege.',
      'Los circuitos que requieren protección diferencial la tienen efectivamente asignada.',
      'La distribución de circuitos entre fases no muestra un desbalanceo evidente entre columnas.',
      'Cada circuito tiene su rótulo en el cuadro de cargas del tablero.',
      'Las salidas mostradas en el modelo 3D corresponden al circuito indicado en la tabla de planificación.',
    ],
    notasIngenieria: [
      notaNormaVerificar(
        'La protección contra sobrecorriente se selecciona para proteger el conductor del circuito, de modo que su capacidad debe coordinarse con el calibre y no elegirse solo por la carga. La coordinación con las protecciones aguas arriba la fija el estudio de coordinación del proyecto.',
        REF.SOBRECORRIENTES,
      ),
      notaNorma(
        'Los interruptores automáticos de baja tensión tienen requisitos propios de instalación, marcación y capacidad de corte en el RETIE; un breaker sin capacidad de corte adecuada al punto de instalación no cumple aunque su corriente nominal sea correcta.',
        REF.INTERRUPTORES_BT,
      ),
      notaNormaVerificar(
        'Un panel de distribución para circuitos ramales de alumbrado y artefactos tiene tope de dispositivos de protección por tablero y debe protegerse en su origen: los dos requisitos están en los Art. 384-15 y 384-16 de la NTC 2050 y condicionan cuántos circuitos caben realmente en el tablero modelado.',
        REF.NTC_MAX_CIRCUITOS_TABLERO,
      ),
      notaNormaVerificar(
        'La capacidad del interruptor se toma de los valores nominales normalizados del Art. 240-6; no existe el breaker de valor intermedio que a veces sale del cálculo.',
        REF.NTC_CORRIENTES_NORMALIZADAS,
      ),
      notaNorma(
        'Cada medio de desconexión debe quedar identificado con su carga de forma legible y permanente. En un tablero de vivienda eso es el directorio de circuitos, y la NTC 2050 lo exige en el Art. 110-22.',
        REF.NTC_IDENT_DESCONEXION,
      ),
      notaNorma(
        'Los tableros deben quedar rotulados de forma que se identifique cada circuito y su carga; el cuadro de cargas es parte del cumplimiento, no un adorno del plano.',
        REF.CELDAS_TABLEROS,
      ),
    ],
    tipsRevit: [
      'Usa la vista "Panel Schedule" del tablero y el parámetro "Circuit Number" para reordenar interruptores arrastrando filas directamente en la tabla.',
      'Aplica un filtro de vista por "Circuit Number" en la vista 3D para resaltar únicamente las salidas de un interruptor específico durante la verificación.',
      'Añade al cuadro de cargas una columna con el calibre del conductor junto a la capacidad del breaker: la incoherencia entre ambos se ve de un vistazo en vez de tener que cruzar dos documentos.',
      'Revisa el parámetro "Load Classification" de cada circuito para confirmar que el balanceo de fases considera el tipo de carga real.',
    ],
  },
  {
    plantillaId: 'PB-02-11',
    nombreOriginal: 'Modelar apantallamiento',
    nombre: 'Modelar el sistema de apantallamiento (pararrayos) de la edificación',
    grupo: '02-modelado',
    subgrupo: 'Puesta a tierra y apantallamiento',
    categoria: 'Sistemas Especiales',
    disciplina: 'Eléctrica',
    dificultad: 4,
    horasEstimadas: 12,
    prioridad: 'Alta',
    dependeDe: [],
    guiaIds: ['M5.6'],
    descripcion: 'Modelado del sistema de protección contra rayos, incluyendo puntas captadoras, conductores de bajada, sus conexiones al sistema de puesta a tierra y los dispositivos de protección contra sobretensiones asociados, según el nivel de protección definido para el proyecto.',
    objetivo: 'Representar en el modelo el sistema de protección contra rayos completo, coherente con el nivel de protección y el método de diseño adoptados, incluida la protección interna contra sobretensiones.',
    requisitos: [
      'Evaluación del nivel de riesgo y nivel de protección contra rayos definidos para el proyecto',
      'Malla de puesta a tierra modelada o en proceso (PB-02-08)',
      'Volumetría final de cubierta del modelo arquitectónico vinculada',
      'Definición de los DPS previstos en tableros',
    ],
    procedimiento: [
      'Confirmar el nivel de protección contra rayos y el método de diseño (mallado, punta Franklin o electrogeométrico) definidos en el estudio del proyecto; el modelador no elige el método.',
      'Colocar las puntas captadoras en cubierta según el método de diseño adoptado, cubriendo también las salientes de cubierta: cuartos de máquinas, tanques y antenas.',
      'Modelar los conductores de bajada desde el sistema captador hasta el punto de conexión con la puesta a tierra, distribuyéndolos por el perímetro en lugar de concentrarlos en una sola fachada.',
      'Verificar la distancia de separación entre las bajantes y las instalaciones metálicas internas, para evitar chispas peligrosas por acoplamiento.',
      'Conectar cada bajante al sistema de puesta a tierra modelado (PB-02-08), integrando el sistema externo con la equipotencialidad general del edificio.',
      'Modelar los dispositivos de protección contra sobretensiones transitorias en los tableros previstos: la protección externa desvía el rayo, pero es el DPS el que protege la instalación interna.',
      'Prever puntos de medición registrables en las bajantes para verificar la continuidad durante el mantenimiento.',
      'Verificar en 3D que ninguna bajante quede sin conexión a la puesta a tierra y que la cantidad y posición de captadores sea consistente con el estudio.',
    ],
    resultadoEsperado: 'Sistema de protección contra rayos modelado con puntas captadoras, bajantes distribuidas, puntos de medición, conexión completa a la puesta a tierra y DPS asociados en los tableros.',
    criteriosVerificacion: [
      'Cada punta captadora tiene al menos una bajante conectada.',
      'Las bajantes están distribuidas por el perímetro, no concentradas en una sola fachada.',
      'Todas las bajantes llegan a un punto de conexión válido en el sistema de puesta a tierra.',
      'Las salientes de cubierta (cuartos de máquinas, tanques, antenas) están cubiertas por el sistema captador.',
      'Los DPS previstos están modelados en sus tableros correspondientes.',
      'Existen puntos de medición registrables para verificar continuidad de las bajantes.',
      'La cantidad de puntas captadoras coincide con la definida en el estudio del proyecto.',
    ],
    notasIngenieria: [
      notaNormaVerificar(
        'El nivel de protección contra rayos y el método de diseño provienen de la evaluación del riesgo del proyecto, no del criterio del modelador. El RETIE fija cuándo se exige el sistema y qué debe cumplir; el dimensionamiento sale del estudio.',
        REF.PROTECCION_RAYOS,
      ),
      notaNorma(
        'La protección externa contra rayos no protege por sí sola los equipos internos: se complementa con dispositivos de protección contra sobretensiones transitorias instalados en los tableros, que tienen su propio artículo en el RETIE.',
        REF.DPS,
      ),
      notaNorma(
        'Los descargadores de sobretensiones tienen sección propia en la NTC 2050 (Sección 280): cuántos se requieren, cómo se seleccionan y dónde se conectan respecto del medio de desconexión de la acometida.',
        REF.NTC_DPS,
      ),
      notaNormaVerificar(
        'La ubicación del descargador dentro de la instalación está reglada, y de ella depende la longitud del conductor de conexión: un DPS bien elegido pero mal ubicado pierde eficacia.',
        REF.NTC_DPS_UBICACION,
      ),
      notaNorma(
        'El sistema de protección contra rayos debe integrarse al sistema equipotencial de puesta a tierra de la edificación, no constituir una tierra separada.',
        REF.SPT_GENERAL,
      ),
    ],
    tipsRevit: [
      'Modela las puntas captadoras como familias basadas en cara para que se adapten a la geometría real de la cubierta del vínculo arquitectónico.',
      'Usa un sistema eléctrico independiente llamado "Apantallamiento" para poder aislarlo del resto de sistemas de puesta a tierra en el diagrama.',
      'Si el diseño usa el método electrogeométrico, modela la esfera rodante como una esfera del radio del nivel de protección y desplázala por la cubierta en 3D: las zonas donde toca la losa son exactamente las que quedan desprotegidas.',
      'Activa "Copiar/Monitorear" sobre el vínculo de cubierta para que las puntas captadoras se actualicen si cambia la volumetría de la cubierta.',
    ],
  },
  {
    plantillaId: 'PB-02-12',
    nombreOriginal: 'Crear toma normal y trifásica en la planta',
    nombre: 'Crear las tomas normales y trifásicas en la planta arquitectónica del proyecto',
    grupo: '02-modelado',
    subgrupo: 'Tomacorrientes y fuerza',
    categoria: 'Tomacorrientes',
    disciplina: 'Eléctrica',
    dificultad: 2,
    horasEstimadas: 10,
    prioridad: 'Alta',
    dependeDe: ['PB-02-03'],
    guiaIds: ['M5.5'],
    descripcion: 'Reemplazo de los marcadores de la propuesta de salidas por las familias definitivas de toma normal y toma trifásica en cada punto de la planta arquitectónica, con la altura de montaje y el grado de protección correctos.',
    objetivo: 'Dejar modeladas con la familia definitiva todas las tomas normales y trifásicas propuestas, con polo a tierra, altura de montaje medida desde piso terminado y grado de protección acorde al ambiente de cada espacio.',
    requisitos: [
      'Propuesta de salidas aprobada (PB-02-03)',
      'Familias de toma normal y toma trifásica cargadas en el proyecto',
      'Criterio de alturas de montaje del proyecto',
      'Grados de protección requeridos por tipo de espacio',
    ],
    procedimiento: [
      'Cargar en el proyecto las familias definitivas de toma normal y toma trifásica, verificando que todas incluyan polo a tierra.',
      'Reemplazar cada marcador de la propuesta de salidas por la familia definitiva correspondiente según su tipo.',
      'Verificar la altura de montaje de cada toma según el criterio de diseño, confirmando que se mide desde el piso terminado y no desde la losa estructural.',
      'Asignar a las tomas de zonas húmedas y exteriores una familia con el grado de protección adecuado al ambiente, no la misma familia de interiores.',
      'Comprobar que las tomas de espacios accesibles a niños o de uso público lleven el tipo de protección adicional que fije el diseño.',
      'Confirmar que cada toma quede hospedada en el muro o superficie correcta del modelo arquitectónico.',
      'Verificar que ninguna toma quede sobre una zona donde no puede ir: dentro de la proyección de un lavamanos, en el interior de una ducha o invadiendo el espacio de trabajo de un tablero.',
      'Revisar en una tabla de planificación que el conteo final de tomas coincide con la propuesta original.',
    ],
    resultadoEsperado: 'Todas las tomas normales y trifásicas de la planta modeladas con su familia definitiva, con polo a tierra, en la altura y posición correctas y con el grado de protección adecuado a cada ambiente.',
    criteriosVerificacion: [
      'Ningún marcador de propuesta permanece en el modelo tras el reemplazo.',
      'Todas las tomas modeladas incluyen polo a tierra.',
      'Cada toma trifásica está identificada con el parámetro de tipo correcto, distinto al de toma normal.',
      'La altura de montaje de las tomas se mide desde piso terminado y corresponde al criterio de diseño definido.',
      'Las tomas de zonas húmedas y exteriores tienen el grado de protección adecuado.',
      'Ninguna toma queda en una posición prohibida por proximidad a agua o por invadir el espacio de trabajo de un tablero.',
      'El conteo de tomas en la tabla de planificación coincide con el de la propuesta de salidas (PB-02-03).',
    ],
    notasIngenieria: [
      notaNormaVerificar(
        'Los tomacorrientes deben tener polo a tierra y una configuración de clavija normalizada; la altura de montaje y las distancias mínimas a puntos de agua dependen del tipo de espacio. Confirmar los valores aplicables al proyecto antes de fijar las alturas.',
        REF.TOMACORRIENTES,
      ),
      notaNormaVerificar(
        'La capacidad nominal y el tipo de tomacorriente admisibles dependen del circuito ramal que los alimenta: el Art. 410-56 de la NTC 2050 tabula qué configuración corresponde a cada amperaje. Es lo que decide la familia de Revit que se usa, no la estética.',
        REF.NTC_TOMAS_CAPACIDAD,
      ),
      notaNorma(
        'El tomacorriente con polo a tierra debe quedar conectado al conductor de puesta a tierra de equipos del circuito; la conexión del terminal de tierra a la caja también está reglada.',
        REF.NTC_TOMAS_POLO_TIERRA,
      ),
      notaNorma(
        'En lugares húmedos o mojados —exteriores, terrazas, cuartos de máquinas, zonas de piscina— el tomacorriente debe llevar tapa con el grado de protección que exige el Art. 410-57, no una tapa cualquiera.',
        REF.NTC_TOMAS_HUMEDOS,
      ),
      notaNorma(
        'Las tomas de zonas húmedas, exteriores y accesibles requieren protección contra falla de aislamiento; el grado de protección de la envolvente debe corresponder al ambiente donde se instala.',
        REF.PROTECCION_AISLAMIENTO,
      ),
    ],
    tipsRevit: [
      'Usa el comando "Reemplazar familia" desde el navegador de proyecto para sustituir en bloque los marcadores por la familia definitiva sin perder su ubicación.',
      'Verifica el parámetro de tipo de familia (número de polos) para diferenciar tomas trifásicas de tomas normales en la tabla de planificación.',
      'Añade a la tabla de tomas una columna con la elevación respecto al nivel: ordenándola detectas en segundos las tomas que quedaron a una altura distinta de la del criterio del proyecto.',
      'Usa una plantilla de vista con filtro por tipo de toma para revisar visualmente la distribución antes de dar por cerrada la planta.',
    ],
  },
  {
    plantillaId: 'PB-02-13',
    nombreOriginal: 'Crear toma normal y trifásica en el cuarto de armarios',
    nombre: 'Crear las tomas normales y trifásicas del cuarto de armarios de medidores',
    grupo: '02-modelado',
    subgrupo: 'Tomacorrientes y fuerza',
    categoria: 'Tomacorrientes',
    disciplina: 'Eléctrica',
    dificultad: 2,
    horasEstimadas: 2,
    prioridad: 'Baja',
    dependeDe: ['PB-02-03'],
    guiaIds: ['M5.5'],
    descripcion: 'Modelado de las tomas normales y trifásicas destinadas al cuarto de armarios de medidores, requeridas para labores de mantenimiento y equipos del cuarto.',
    objetivo: 'Dejar modeladas las tomas de mantenimiento del cuarto de armarios de medidores, con su circuito de alimentación asociado y sin invadir el espacio de trabajo frente a los tableros.',
    requisitos: [
      'Propuesta de salidas del cuarto de armarios definida (PB-02-03)',
      'Ubicación del cuarto de armarios confirmada en el modelo arquitectónico',
      'Espacio de trabajo frente a tableros reservado (PB-01-02)',
    ],
    procedimiento: [
      'Ubicar el cuarto de armarios de medidores en el modelo arquitectónico vinculado.',
      'Colocar la familia definitiva de toma normal en el punto propuesto para mantenimiento general.',
      'Colocar la familia definitiva de toma trifásica si el cuarto requiere alimentar equipos trifásicos.',
      'Verificar que ninguna toma quede dentro del espacio de trabajo reservado frente a los tableros ni obstruya la maniobra de las puertas de los armarios.',
      'Conectar ambas tomas a un circuito del tablero que sirve el cuarto de armarios, con protección diferencial por ser un punto de uso de herramienta portátil.',
      'Comprobar en la vista 3D que la posición de las tomas no interfiera con la apertura de puertas de los armarios.',
    ],
    resultadoEsperado: 'Tomas normales y trifásicas del cuarto de armarios de medidores modeladas y conectadas a su circuito, sin invadir el espacio de trabajo de los tableros.',
    criteriosVerificacion: [
      'El cuarto de armarios cuenta con al menos una toma normal modelada.',
      'La toma trifásica está presente si el cuarto tiene equipos que la requieran, según la propuesta de salidas.',
      'Ninguna toma invade el espacio de trabajo reservado frente a los tableros.',
      'Ambas tomas están conectadas a un circuito válido con protección diferencial.',
      'La posición de las tomas no interfiere con la apertura de puertas de los armarios en el modelo 3D.',
    ],
    notasIngenieria: [
      notaNorma(
        'El espacio de trabajo frente a tableros debe permanecer libre; una toma de mantenimiento ubicada dentro de esa zona con una herramienta conectada la obstruye justo cuando más se necesita despejada.',
        REF.ESPACIOS_MONTAJE,
      ),
      notaNormaVerificar(
        'El fondo, el ancho y la altura libres del espacio de trabajo frente al armario están tabulados en el Art. 110-16 de la NTC 2050: es una zona que no puede invadirse con tomas, tuberías ni mobiliario.',
        REF.NTC_ESPACIO_TRABAJO,
      ),
      notaNorma(
        'Las tomas destinadas a herramienta portátil en cuartos técnicos requieren polo a tierra y protección contra falla de aislamiento.',
        REF.TOMACORRIENTES,
      ),
    ],
    tipsRevit: [
      'Revisa la vista 3D con la puerta de los armarios en posición abierta (parámetro de familia) para confirmar que la toma no queda obstruida.',
      'Si modelaste el espacio de trabajo como sólido genérico en PB-01-02, incluye las tomas en la comprobación de interferencias contra él: la invasión aparece sola.',
      'Usa el mismo circuito del cuarto de armarios para ambas tomas cuando la carga total lo permita, y verifícalo en la tabla de planificación del panel.',
      'Aplica la etiqueta de "Panel" y "Circuit Number" visible en la vista de planta para facilitar la trazabilidad durante la revisión de obra.',
    ],
  },
  {
    plantillaId: 'PB-02-14',
    nombreOriginal: 'Modelar tubería salidas',
    nombre: 'Modelar la tubería de canalización eléctrica para las salidas de tomacorriente y fuerza',
    grupo: '02-modelado',
    subgrupo: 'Canalizaciones',
    categoria: 'Ductos y Bandejas',
    disciplina: 'Eléctrica',
    dificultad: 2,
    horasEstimadas: 12,
    prioridad: 'Media',
    dependeDe: ['PB-02-12'],
    guiaIds: ['M2.1', 'M2.2'],
    descripcion: 'Modelado de la tubería (conduit) que canaliza los conductores desde cada tomacorriente o salida de fuerza hasta la caja de paso o el tablero correspondiente.',
    objetivo: 'Dejar modelada la canalización física completa entre cada salida y su punto de conexión, con diámetros acordes al porcentaje de ocupación y cajas de paso en los tramos que lo exigen, lista para el cálculo de cantidades.',
    requisitos: [
      'Tomas normales y trifásicas modeladas en planta (PB-02-12, PB-02-13)',
      'Circuitos de tomacorriente ya creados',
      'Criterio de número máximo de curvas entre cajas de paso',
    ],
    procedimiento: [
      'Seleccionar el sistema eléctrico de cada circuito de tomacorriente/fuerza a canalizar.',
      'Usar el comando de generación automática de conductos ("Generate Layout") o modelar manualmente con "Conduit" para trazar la tubería entre cada salida y la caja de paso.',
      'Ajustar el trazado para respetar retiros mínimos a otras canalizaciones y elementos estructurales.',
      'Asignar el diámetro de tubería según el porcentaje máximo de ocupación admisible para el número y calibre de conductores que contendrá, no por el diámetro geométrico de los cables.',
      'Insertar cajas de paso donde el tramo acumule más curvas de las admitidas o supere la longitud a partir de la cual el alambrado deja de ser viable.',
      'Verificar que la tubería no atraviese elementos estructurales sin la autorización de estructura ni comparta canalización con sistemas de corrientes débiles.',
      'Revisar los cruces con muros y losas cortafuego para modelar el sello correspondiente.',
      'Verificar en 3D que toda salida quede conectada a la red de tubería, sin tramos sueltos.',
      'Revisar en una tabla de planificación la longitud total de tubería modelada por tramo.',
    ],
    resultadoEsperado: 'Red de tubería para salidas de tomacorriente y fuerza modelada completamente, conectando cada toma con su caja de paso o tablero, con diámetros por ocupación, cajas de paso y sellos cortafuego resueltos.',
    criteriosVerificacion: [
      'Toda toma normal o trifásica modelada tiene un tramo de tubería conectado.',
      'No existen tramos de tubería sueltos sin conexión en ambos extremos.',
      'El diámetro de cada tramo respeta el porcentaje máximo de ocupación para sus conductores.',
      'Ningún tramo entre cajas de paso supera el número de curvas admitido.',
      'Los cruces con muros y losas cortafuego tienen sello modelado.',
      'La tabla de planificación de tubería no muestra longitudes en cero para ningún tramo activo.',
    ],
    notasIngenieria: [
      notaNormaVerificar(
        'El diámetro de la canalización lo fija el porcentaje máximo de ocupación admisible, que depende del número de conductores. El número máximo de curvas entre cajas de paso también está reglado: superarlo hace inviable el alambrado en obra aunque el modelo se vea correcto.',
        REF.CANALIZACIONES,
      ),
      notaNorma(
        'Las cajas y conduletas tienen requisitos propios de accesibilidad y capacidad; una caja de paso inaccesible tras el acabado incumple aunque esté modelada.',
        REF.CAJAS_CONDULETAS,
      ),
      notaNormaVerificar(
        'El volumen mínimo de la caja se calcula contando conductores, dispositivos y accesorios según el Art. 370-16 de la NTC 2050. Una caja de 5800 elegida por costumbre puede quedar corta en cuanto entran tres circuitos.',
        REF.NTC_VOLUMEN_CAJAS,
      ),
      notaNorma(
        'Las cajas de paso y de empalme deben quedar accesibles sin romper el acabado; el Art. 370-29 lo exige explícitamente y es un hallazgo típico de inspección en obra terminada.',
        REF.NTC_CAJAS_ACCESIBLES,
      ),
      notaNormaVerificar(
        'El porcentaje de ocupación admisible está en el Cuadro 1 del Capítulo 9 de la NTC 2050 y el número máximo de conductores por diámetro, en los cuadros del Anexo C.',
        REF.NTC_OCUPACION_TUBERIA,
      ),
      notaNormaVerificar(
        'La capacidad de corriente del conductor sale del Art. 310-15, corregida por temperatura ambiente y por número de conductores en tensión dentro de la misma canalización.',
        REF.NTC_AMPACIDAD,
      ),
    ],
    tipsRevit: [
      'Usa el comando "Generate Layout" desde la pestaña Sistemas para trazar automáticamente la tubería del circuito seleccionado y luego ajusta manualmente los tramos que crucen zonas críticas.',
      'Configura las reglas de dimensionamiento (Sizing Settings) del sistema de conductos antes de generar el trazado para que el diámetro se calcule automáticamente.',
      'El trazado automático optimiza la longitud, no el número de curvas: revisa siempre los tramos generados y añade cajas de paso donde se acumulen codos.',
      'Usa una tabla de planificación de "Conduit" agrupada por sistema para revisar la longitud total y detectar tramos con longitud cero.',
    ],
  },
  {
    plantillaId: 'PB-02-15',
    nombreOriginal: 'Modelar tubería iluminación',
    nombre: 'Modelar la tubería de canalización eléctrica para los circuitos de iluminación',
    grupo: '02-modelado',
    subgrupo: 'Canalizaciones',
    categoria: 'Ductos y Bandejas',
    disciplina: 'Eléctrica',
    dificultad: 2,
    horasEstimadas: 12,
    prioridad: 'Media',
    dependeDe: ['PB-02-05'],
    guiaIds: ['M2.1', 'M2.2'],
    descripcion: 'Modelado de la tubería (conduit) que canaliza los conductores de los circuitos de iluminación desde cada luminaria o punto de control hasta la caja de paso o el tablero correspondiente.',
    objetivo: 'Dejar modelada la canalización física completa de los circuitos de iluminación, separando los circuitos de emergencia de los normales, lista para el cálculo de cantidades y la documentación.',
    requisitos: [
      'Luminarias e interruptores de control modelados en planta',
      'Circuitos de iluminación ya creados',
      'Identificación de las luminarias que pertenecen al alumbrado de emergencia',
    ],
    procedimiento: [
      'Seleccionar el sistema eléctrico de cada circuito de iluminación a canalizar.',
      'Trazar la tubería entre cada luminaria, su interruptor de control y la caja de paso correspondiente.',
      'Canalizar los circuitos de iluminación de emergencia y evacuación por rutas independientes de los circuitos normales, para que una falla o intervención en el alumbrado normal no comprometa el de emergencia.',
      'Ajustar el trazado en cielos falsos o losas según el criterio constructivo del proyecto, manteniendo registrables las cajas de paso.',
      'Asignar el diámetro de tubería según el porcentaje de ocupación admisible para el número y calibre de conductores que contendrá.',
      'Verificar que los conductores de iluminación no compartan canalización con sistemas de corrientes débiles ni con circuitos de otra tensión sin la separación exigida.',
      'Verificar en 3D que toda luminaria e interruptor queden conectados a la red de tubería modelada.',
      'Revisar en una tabla de planificación la longitud total de tubería de iluminación por tramo.',
    ],
    resultadoEsperado: 'Red de tubería para circuitos de iluminación modelada completamente, conectando luminarias, interruptores y cajas de paso, con las rutas de emergencia independientes de las normales.',
    criteriosVerificacion: [
      'Toda luminaria modelada tiene un tramo de tubería conectado hasta su interruptor de control.',
      'Los circuitos de iluminación de emergencia van por canalización independiente de los normales.',
      'No existen tramos de tubería sueltos sin conexión en ambos extremos.',
      'El diámetro de cada tramo respeta el porcentaje de ocupación para sus conductores.',
      'Las cajas de paso quedan registrables tras el acabado previsto.',
      'La tabla de planificación de tubería de iluminación no muestra longitudes en cero para ningún tramo activo.',
    ],
    notasIngenieria: [
      notaNorma(
        'Las redes eléctricas de los sistemas de iluminación tienen requisitos generales propios en el RETIE, que se suman a los del RETILAP sobre el diseño luminotécnico.',
        REF.REDES_ILUMINACION,
      ),
      notaNorma(
        'El alumbrado de emergencia forma parte de los sistemas de emergencia y debe ser independiente del alumbrado normal; compartir canalización compromete esa independencia.',
        REF.SISTEMAS_EMERGENCIA,
      ),
      notaNorma(
        'La Sección 700 de la NTC 2050 exige que el alambrado de emergencia sea independiente del normal, salvo las excepciones que ella misma lista: eso obliga a canalización separada, no solo a circuito separado.',
        REF.NTC_EMERGENCIA,
      ),
      notaNorma(
        'Las salidas de alumbrado obligatorias por espacio y su control están regladas en el Art. 210-70; el trazado de la tubería tiene que dar servicio a todas ellas.',
        REF.NTC_SALIDAS_ALUMBRADO,
      ),
      notaNormaVerificar(
        'El porcentaje de ocupación y la accesibilidad de las cajas de paso aplican igual en iluminación que en fuerza; verificar los valores para el tipo de canalización usado en cielos falsos.',
        REF.CANALIZACIONES,
      ),
    ],
    tipsRevit: [
      'Traza primero los tramos entre interruptor y luminaria antes de usar el trazado automático, ya que el orden de conexión define el recorrido de "Generate Layout".',
      'Usa la vista de cielo falso reflejado (Reflected Ceiling Plan) para ubicar con precisión el trazado de tubería respecto a la disposición real de luminarias.',
      'Crea un subtipo de conduit exclusivo para emergencia y píntalo con un filtro de vista: cualquier luminaria de evacuación conectada a la canalización normal se ve de inmediato en la planta.',
      'Filtra la tabla de planificación de "Conduit" por el sistema de iluminación para separar su longitud de la tubería de tomacorriente al calcular cantidades.',
    ],
  },
  {
    plantillaId: 'PB-02-16',
    nombreOriginal: 'Cálculo de transformador',
    nombre: 'Recalcular y verificar la capacidad definitiva del transformador con las cargas del proyecto arquitectónico',
    grupo: '02-modelado',
    subgrupo: 'Acometidas y subestación',
    categoria: 'Acometidas',
    disciplina: 'Eléctrica',
    dificultad: 4,
    horasEstimadas: 8,
    prioridad: 'Alta',
    dependeDe: ['PB-01-04'],
    guiaIds: ['M5.1'],
    descripcion: 'Recálculo de la capacidad del transformador a partir de la carga instalada real, obtenida de los circuitos y tableros ya modelados del proyecto arquitectónico, para confirmar o ajustar la capacidad estimada en el predimensionamiento.',
    objetivo: 'Verificar que la capacidad del transformador seleccionada en el predimensionamiento (PB-01-04) sea suficiente para la carga real del proyecto modelado, ajustarla si es necesario y dejar la memoria de cálculo definitiva con sus factores justificados.',
    requisitos: [
      'Cálculo preliminar del transformador disponible (PB-01-04)',
      'Tableros y circuitos del proyecto modelados con sus cargas conectadas',
      'Factores de demanda y coincidencia definidos para el tipo de proyecto',
      'Previsión de crecimiento de carga acordada con el cliente',
    ],
    procedimiento: [
      'Extraer del modelo, mediante tablas de planificación de paneles, la carga instalada total de todos los tableros del proyecto.',
      'Verificar antes de sumar que ningún tablero tenga circuitos sin carga asignada: una tabla incompleta produce una demanda subestimada que parece correcta.',
      'Aplicar los factores de demanda y coincidencia correspondientes a cada tipo de carga (iluminación, tomas, fuerza, servicios comunes), documentando el criterio de origen de cada factor.',
      'Calcular la demanda máxima proyectada resultante en kVA y añadir la previsión de crecimiento acordada.',
      'Comparar la demanda máxima calculada contra la capacidad del transformador estimada en el cálculo preliminar (PB-01-04).',
      'Ajustar la capacidad nominal del transformador en el modelo si la demanda real supera o queda muy por debajo de la capacidad preliminar.',
      'Verificar que el cambio de capacidad no invalide decisiones ya tomadas: área de subestación, ventilación (PB-02-17), sección del alimentador y protecciones del TGBT.',
      'Documentar la memoria de cálculo definitiva con la carga instalada, los factores aplicados y la capacidad final seleccionada.',
    ],
    resultadoEsperado: 'Capacidad definitiva del transformador verificada o ajustada a partir de la carga real del proyecto modelado, con memoria de cálculo documentada y con las decisiones dependientes revisadas.',
    criteriosVerificacion: [
      'La carga instalada total fue extraída de las tablas de planificación de paneles del modelo, no estimada manualmente.',
      'Ningún tablero del modelo tiene circuitos sin carga asignada al momento de la extracción.',
      'Los factores de demanda aplicados están documentados con su criterio de origen en la memoria de cálculo.',
      'La capacidad nominal del transformador en el modelo coincide con el resultado del cálculo definitivo.',
      'Se revisó el impacto del resultado sobre el área de subestación, la ventilación y el alimentador.',
      'La memoria de cálculo compara explícitamente el resultado definitivo contra el cálculo preliminar (PB-01-04).',
    ],
    notasIngenieria: [
      notaNorma(
        'La memoria de cálculo es parte del diseño exigible y debe estar firmada por el profesional competente responsable; la extracción de cargas del modelo es un insumo suyo, no un sustituto de su criterio.',
        REF.RESPONSABILIDAD_DISENADOR,
      ),
      notaNormaVerificar(
        'Los factores de demanda y coincidencia dependen del tipo de proyecto y de la normativa del operador de red local; no asumir valores fijos sin confirmarlos con el código eléctrico aplicable y sin dejarlos justificados en la memoria.',
        REF.CRITERIOS_DISENO,
      ),
      notaNormaVerificar(
        'Para el cálculo definitivo en vivienda multifamiliar, la NTC 2050 admite el método opcional del Art. 220-32 y, cuando la empresa local de energía tiene reglamentación propia, el cálculo del Art. 220-37. Dejar escrito en la memoria cuál se aplicó y por qué.',
        REF.NTC_OPCIONAL_OR,
      ),
      notaNorma(
        'El transformador de potencia y distribución debe cumplir los requisitos de instalación del RETIE, que condicionan además el cuarto donde se aloja.',
        REF.TRANSFORMADORES,
      ),
    ],
    tipsRevit: [
      'Usa una tabla de planificación de "Panel Schedule" a nivel de proyecto para sumar la carga conectada de todos los tableros sin recalcular manualmente fuera de Revit.',
      'Antes de extraer la carga, ordena la tabla por carga conectada: los circuitos con valor cero salen agrupados arriba y son exactamente los que falsean el total.',
      'Registra el resultado del cálculo definitivo en un parámetro compartido de la subestación (por ejemplo "Capacidad_Transformador_kVA") para que quede trazable en el modelo.',
      'Compara el parámetro de capacidad preliminar (PB-01-04) y definitivo en la misma tabla de planificación de equipo para evidenciar el ajuste ante el equipo de diseño.',
    ],
  },
  {
    plantillaId: 'PB-02-17',
    nombreOriginal: 'Cálculo del dámper',
    nombre: 'Calcular las dimensiones del dámper de ventilación de la subestación',
    grupo: '02-modelado',
    subgrupo: 'Acometidas y subestación',
    categoria: 'Modelado',
    disciplina: 'Eléctrica',
    dificultad: 3,
    horasEstimadas: 4,
    prioridad: 'Media',
    dependeDe: ['PB-01-01', 'PB-02-16'],
    guiaIds: ['M5.1'],
    descripcion: 'Cálculo del área de ventilación (dámper) requerida para la disipación térmica del cuarto de transformador, a partir de las pérdidas de potencia del transformador seleccionado en el cálculo definitivo.',
    objetivo: 'Determinar y modelar el área de dámper de ventilación necesaria para el cuarto de subestación, en función de la capacidad definitiva del transformador y conservando el grado de protección y la resistencia al fuego del recinto.',
    requisitos: [
      'Capacidad definitiva del transformador calculada (PB-02-16)',
      'Pérdidas de potencia del transformador según ficha técnica del fabricante',
      'Dimensiones del cuarto de subestación confirmadas en el modelo',
      'Resistencia al fuego y grado de protección exigidos al cuarto',
    ],
    procedimiento: [
      'Obtener las pérdidas de potencia (en watts) del transformador según su capacidad definitiva (PB-02-16), tomadas de la ficha técnica y no estimadas de la potencia nominal.',
      'Calcular el área de ventilación requerida a partir de las pérdidas térmicas y el criterio de diseño adoptado para el proyecto.',
      'Distribuir el área calculada entre la abertura de entrada baja y la de salida alta previstas en PB-01-06, en lugar de concentrarla en una sola.',
      'Verificar en el modelo las dimensiones disponibles en el muro o losa donde se ubicará cada dámper.',
      'Modelar cada dámper con el área correspondiente, hospedado en el elemento arquitectónico real del cuarto.',
      'Verificar que el dámper conserve el grado de protección del recinto contra ingreso de agua, animales y objetos, y que su rejilla no reduzca el área libre por debajo de la calculada.',
      'Confirmar que la abertura no comprometa la resistencia al fuego exigida al cerramiento, previendo compuerta cortafuego si el diseño lo requiere.',
      'Confirmar que el área libre modelada sea igual o mayor al área mínima calculada.',
    ],
    resultadoEsperado: 'Dámperes de ventilación de la subestación modelados con el área libre calculada a partir de las pérdidas térmicas del transformador definitivo, conservando el grado de protección y la resistencia al fuego del recinto.',
    criteriosVerificacion: [
      'El área libre de los dámperes modelados es igual o mayor al área mínima resultante del cálculo.',
      'El área está repartida entre abertura de entrada baja y salida alta, no concentrada en una sola.',
      'El cálculo del área de ventilación referencia explícitamente la capacidad definitiva del transformador (PB-02-16) y las pérdidas de la ficha técnica.',
      'El dámper conserva el grado de protección exigido al recinto.',
      'La abertura no compromete la resistencia al fuego del cerramiento, o lleva compuerta cortafuego.',
      'El dámper está hospedado en un elemento arquitectónico real del cuarto de subestación, no como elemento flotante.',
    ],
    notasIngenieria: [
      notaNormaVerificar(
        'El área calculada es área LIBRE de paso: la rejilla y las lamas del dámper reducen el área efectiva respecto al hueco. Verificar el porcentaje de área libre del producto contra su ficha técnica antes de dar por buena la dimensión.',
        REF.COMPUERTAS_VENTILACION,
      ),
      notaNorma(
        'El requisito de ventilación del recinto del transformador es de la NTC 2050 (Art. 450-9): el dámper es el medio, la norma fija que el calor de las pérdidas debe poder evacuarse.',
        REF.NTC_TRANSFORMADOR_VENTILACION,
      ),
      notaNorma(
        'Las subestaciones de media tensión tipo interior o en edificaciones deben conservar sus condiciones de ventilación, grado de protección y resistencia al fuego de forma simultánea; una abertura mal resuelta satisface una y rompe otra.',
        REF.SUBESTACION_MT_INTERIOR,
      ),
    ],
    tipsRevit: [
      'Modela el dámper como familia basada en muro (wall-based) para que su posición se mantenga asociada al cerramiento del cuarto de subestación.',
      'Registra el área calculada, el área del hueco y el área libre efectiva en parámetros compartidos separados: la diferencia entre las dos últimas es la que suele hacer fallar la verificación en obra.',
      'Usa una vista de alzado del cuarto de subestación para verificar que la altura de montaje del dámper permita el flujo de aire cruzado con las aberturas opuestas.',
    ],
  },
];
